- user/apps.md
Added [CI Status](https://ci-status.com/) to the tool list.
> Added CI Status

- _layouts/en.html
- user/deployment/packagecloud.md
Hi:
This PR adds documentation for the packagecloud provider as per comments by @BanzaiMan on https://github.com/travis-ci/dpl/pull/203.
> Add packagecloud documentation

- _layouts/en.html
> Happy New Year!

- _layouts/en.html
- user/deployment.md
- user/deployment/biicode.md
- user/languages/c.md
- user/languages/cpp.md
> biicode deploy in travis-ci docs

- user/languages/php.md
Let's update the docs to reflect the current system.
> Updated the php docs

- user/languages/go.md
> Update go lang docs regarding gimme, godeps, and gobuild_args

- user/languages/dart.md
Related to https://github.com/travis-ci/travis-build/pull/387
> remove warning for tests in dart

- user/deployment/npm.md
> Update npm.md : Missing line for email

- user/using-postgresql.md
> PostgreSQ*L*

- _layouts/en.html
- index.html
- user/ci-environment.md
- user/getting-started.md
- user/languages/index.md
- user/languages/r.md
This is the documentation complement to [this travis-build pull
request](https://github.com/travis-ci/travis-build/pull/386).
> Add documentation for R support.

- user/languages/csharp.md
Mainly about https://github.com/travis-ci/travis-build/pull/394
If you have any other improvements to the docs in mind, we should get them done as part of this PR :)
/cc @Joshua-Anderson @nterry
> C#: docs about Mono version switching and a few minor fixes

- user/database-setup.md
> switch wget to curl for elastic search install line

- user/caching.md
Fixes travis-ci/travis-ci#3357
> Caching: Clarify 'custom install step' and give pip/ccache workarounds

- user/build-configuration.md
- user/customizing-the-build.md
- user/installing-dependencies.md
- user/osx-ci-environment.md
- user/workers/container-based-infrastructure.md
- user/workers/standard-infrastructure.md
> Updating docs for switch to docker as default Linux queue

- user/build-environment-updates/2015-04-09.md
* Change logs reflect those shown in https://github.com/travis-ci/travis-cookbooks/compare/updates-2015-02-03...updates-2015-04-09
* MySQL downgrade instructions have been tested
> Add Build Environment update schedule for 2015-04-09

- user/languages/csharp.md
Fixes https://github.com/travis-ci/docs-travis-ci-com/issues/226
Also add a note about the Mono bug that causes xunit 2.0 to hang.
> C#: use xunit.console.clr4.exe in the sample and add note about bug with xunit2

- user/gui-and-headless-browsers.md
This documents a fix for Karma I had to add based on some funky build failures w/ [petejohanson/hy-res](https://travis-ci.org/petejohanson/hy-res/builds/59666823).
> Troubleshooting docs on Karma + FF timeouts

- user/getting-started.md
- user/languages/haxe.md
To sync with https://github.com/travis-ci/travis-build/pull/452
> haxe default version is 3.2.0

- user/deployment/gcs.md
> Updating GCS to what is currently implemented.

- user/languages/community-supported-languages.md
To formally document what we have been doing so far when a new community language is added.
> Formally document process to add a new community-supported language

- user/gui-and-headless-browsers.md
Signed-off-by: Zhaofeng Li <hello@zhaofeng.li>
> gui-and-headless-browsers.md: Fix link to deprecated page

- user/ci-environment.md
Fix typo: "slight" to "slightly"
> Fix typo in ci-environment.md

- _includes/sidebar.html
- user/triggering-builds.md
I haven't linked it on main page for now, I'm not sure if I should do it.
> Docs for triggering builds API

- user/customizing-the-build.md
Hi, thank you as always.
> via https://github.com/travis-ci/travis-ci/issues/4103
> Change `*deployment` -> `*deploy`

- user/ci-environment.md
- user/environment-variables.md
Fix style of multi-level list. Indent the 2nd level list.
Fix issue of "settings-env-vars.png" do not shown in figure tag.
> Gh pages fix

- user/languages/crystal.md
ref: https://github.com/travis-ci/travis-build/pull/465
> Add crystal docs

- user/languages/community-supported-languages.md
This PR fixes a minor grammatical issue on the community supported languages page as well as improves sentence flow and clarity in some places.
> Minor fixes to community supported languages page

- user/browser-extensions.md
- user/build-environment-updates.md
- user/caching.md
- user/ci-environment.md
- user/coverity-scan.md
- user/database-setup.md
- user/deployment/pypi.md
- user/deployment/releases.md
- user/deployment/s3.md
- user/travis-pro.md
@joshk giving back to the OS community.
> More grammar corrections.

- _includes/sidebar.html
- user/migrating-from-legacy.md
This explain how to migrate from legacy to container-based infra.
It includes sections on:
- The benefits
- How to install apt sources and packages 
- How to install custom software.
> add guide for migrating from legacy to container infra

- user/migrating-from-legacy.md
https://travis-ci.org/openquery/mariadb-server/jobs/70511922
as per https://github.com/travis-ci/travis-ci/issues/3772
> fix: migrating-from-legacy use of compound bash in yaml

- user/code-climate.md
to use the correct executable name
> Updating JavaScript section in CodeClimate guide

- user/migrating-from-legacy.md
Based on tweet conversation, https://twitter.com/agentdero/status/621424901841223681, I
thought a tl;dr might be useful
> tl;dr on migrating to container infrastructure

- user/notifications.md
This is a companion to https://github.com/travis-ci/travis-tasks/pull/28
> add docs on pushover

- user/languages/rust.md
A few updates to content, mentioning explicit version support, and adding a configuration that tests everything.
> Update Rust info

- user/notifications.md
> Clarifying Notification settings

- assets/stylesheets/_utils.sass
- user/apps.md
> add some styles for the app page

- user/private-dependencies.md
Hat tip to @dentarg for finding it!
> Fixed link to encrypting-files.md

- _includes/sidebar.html
- user/docker.md
Currently covers downloading and using a docker image, and building an image from a dockerfile.
Will add pushing to a Docker remote repo at some point.
> Adding docs on using Docker

- _data/deployments.yml
- _data/lists.yml
- user/deployment/bintray.md
Documentation for the new recently added Bintray Provider.
> Bintray Provider documentation.

- user/gui-and-headless-browsers.md
See https://github.com/travis-ci/travis-ci/issues/4387
> Recommend -a option for xvfb

- user/speeding-up-the-build.md
Hi, I've updated info about knapsack gem since it supports minitest.
My last PR: https://github.com/travis-ci/docs-travis-ci-com/pull/150
> Add knapsack minitest support on speeding up the build page

- user/deployment/packagecloud.md
> Document packagecloud package_glob option.

- user/deployment/boxfuse.md
To account for bug fix in https://github.com/travis-ci/dpl/pull/326
> Boxfuse deployment provider: adjust docs for latest fix

- user/deployment/azure-web-apps.md
> Add Docs for dpl Azure Web Apps Provider

- user/languages/go.md
Add tags to pages for terms that are not in the document.
> Adding tags to enhance search results

- user/languages/go.md
I wasn't sure at what column I should flow the text here -- some of this file appears to be flowed somewhere around 122 characters, but then other parts are around 54 or so, so I'm really confused, but happy to update/reflow to whatever! :+1:
> Add some simple documentation about "go_import_path"

- user/deployment/google-app-engine.md
Sorry - missed a few small things.
> Typos and minor fixes

- user/languages/python.md
> directory spelling fix.

- _includes/header.html
- index.html
- user/ci-environment-trusty-beta.md
- user/ci-environment.md
- user/languages/python.md
- user/trusty-ci-environment.md
Docs for trusty beta, driven by https://github.com/travis-pro/team-blue/issues/139
> Initial cut of docs for Trusty beta

- user/languages/crystal.md
Documentation for https://github.com/travis-ci/travis-build/pull/526
> Crystal: document nightly builds

- user/getting-started.md
- user/languages/haxe.md
Depends on https://github.com/travis-ci/travis-build/pull/527
> haxe: set default version to latest release (3.2.1)

- user/languages/objective-c.md
I'm pretty sure that these are all the right simulators and stuff, but perhaps someone like @henrikhodne, @cotsog, or @MariadeAnton would like to look over it beforehand?
> adding info about Xcode 7.0.1, Xcode 7.1 releases.

- user/apt.md
> APT addon page now clearer about its availability.

- user/languages/objective-c.md
> Adding info for Xcode 7.2 Beta

- user/customizing-the-build.md
The current order is documented in a comment to an open pull request to travis-build:
<https://github.com/travis-ci/travis-build/pull/329#issuecomment-62975954>
> Correct build step order

- user/languages/c.md
- user/languages/cpp.md
- user/languages/erlang.md
- user/languages/go.md
- user/languages/haskell.md
- user/languages/perl.md
- user/languages/php.md
This pull-requests fixes some typos in the documentation.
> Fix some typos.

- 404.html
- Gemfile
- Gemfile.lock
- Procfile
- Rakefile
- assets/stylesheets/main.sass
- config.ru
This PR modifies the app so that it can be deployed to Heroku.
The change in the server is somewhat arbitrary, so I'm up to suggestions if anyone has strong opinions.
> Allow standalone deployment to Heroku

- user/notifications.md
This is realized by https://github.com/travis-ci/travis-hub/pull/62
> Document ability to disable PR notifications for Hipchat and Slack

- _data/deployments.yml
- _data/snippets.yml
- user/deployment/atlas.md
Fix for travis-pro/team-sapphire/issues/174
> Docs for Deploy to Atlas

- user/languages/javascript-with-nodejs.md
This corresponds to https://github.com/travis-ci/travis-build/pull/504
> Add documentation on npm via package.json

- user/languages/javascript-with-nodejs.md
This corresponds to https://github.com/travis-ci/travis-build/pull/576.
> Document build error when specified Node.js is unavailable

- user/languages/javascript-with-nodejs.md
Reverts travis-ci/docs-travis-ci-com#467
> Revert "Add documentation on npm via package.json"

- user/encrypting-files.md
Base on this comment of mine: https://github.com/travis-ci/travis-ci/issues/3637#issuecomment-91336199
Fixes https://github.com/travis-ci/travis-ci/issues/3637.
> Fix gpg encryption invocation

- README.md
I added a link to reference the MIT License, so it matches other parts of the README.md. Also, corrected a run on sentence.
> Added link for MIT license and corrected run on.

- user/deployment/azure-web-apps.md
- user/deployment/cloudcontrol.md
- user/deployment/codedeploy.md
- user/deployment/deis.md
- user/deployment/heroku.md
- user/deployment/npm.md
- user/deployment/openshift.md
Documents issues discussed in https://github.com/travis-ci/travis-ci/issues/4006
> Add notes on `.gitignore` files for relevant providers

- index.html
- user/notifications.md
@MariadeAnton good catch on the settings (I've also fixed the quotes and changed the email domain).
Shippit if you're happy!
> Clarifying email settings

- user/caching.md
- user/languages/r.md
This reflects recent changes in the implementation.
> Updates to in R documentation

- user/deployment/releases.md
> Add info on using releases to deploy to GH:E

- user/languages/haskell.md
Following from #490, I put this on the `gh-pages` branch, so it should be a quick merge.
> Add better haskell examples

- user/hostname.md
Resolves https://github.com/travis-ci/travis-ci/issues/5227
> Document hostname addon

- user/installing-dependencies.md
Corresponds to https://github.com/travis-ci/travis-build/issues/656
> Document `apt-get install` failure errors build

- user/languages/python.md
Change "Travis CI support" to "Travis CI supports"
> Small grammar fix

- index.html
- user/ip-addresses.md
I'm not quite happy with the wording here, for example almost every paragraph starts with "For". So I'd love some feedback on how to better word this.
> Add a docs page detailing the IP addresses each build environment uses

- user/languages/julia.md
See https://github.com/travis-ci/travis-build/pull/679
cc: @tkelman @staticfloat @ninjin
> add simonbyrne to Julia maintainer list

- user/uploading-artifacts.md
Fixes https://github.com/travis-ci/artifacts/issues/57
> Fix artifacts addon minimal configuration example

- _data/xcodes.yml
from beta to general availability! :tada:
> Increment Xcode 7.3 version number

- user/deployment/releases.md
I believe this link would help with the user experience.
> Add link to travis cli on the deployment releases page.

- user/languages/r.md
> Add information on using packages from a subdirectory

- user/languages/dart.md
See https://github.com/travis-ci/travis-build/pull/686
CC @a14n
> Updates to dart instructions to align with recent pull request

- user/database-setup.md
> Fix default PostgreSQL version

- user/notifications.md
Follow-up to https://github.com/travis-ci/travis-tasks/pull/56
@BanzaiMan
> Add some documentation for elapsed_time

- user/languages/php.md
Fixes https://github.com/travis-ci/travis-ci/issues/5621
> Drop mention of mongodb.so for older PHP versions

- user/deployment/s3.md
Fix for https://github.com/travis-ci/docs-travis-ci-com/issues/519
> S3 removal fix, and cleanup

- user/firefox.md
> Clarify text about firefox addon (closes #559)

- user/osx-ci-environment.md
- Help reduce confusion, per
https://github.com/travis-ci/travis-ci/issues/5941#issuecomment-213604181
> Removing reference to `RabbitMQ`

- user/languages/objective-c.md
- user/osx-ci-environment.md
Fix for https://github.com/travis-pro/team-sapphire/issues/254
> Moving iOS stuff to the environment reference

- index.html
> Fix typo in index

- user/caching.md
See https://github.com/travis-ci/travis-build/pull/710
and https://github.com/travis-ci/travis-ci/issues/4470
> Document `cache: cargo` for Rust

- _includes/sidebar.html
- assets/javascripts/main.js
- assets/stylesheets/_base.sass
- assets/stylesheets/_layout.sass
- assets/stylesheets/_mixins.sass
- assets/stylesheets/_sidebar.sass
- assets/stylesheets/_utils.sass
- assets/stylesheets/_vars.sass
- assets/stylesheets/main.sass
- images/ui/icon-arrowtabs.svg
change some colors, add sidebar toggle, persist open section.
The tricky part is knowing exactly which page is active. In theory we could also store the name of the clicked link. But this is a good first step
> Sidebar toggle

- _data/xcodes.yml
- user/osx-ci-environment.md
- Added 7.3.1 version
- Tweaked so that we can display the Xcode minor version but the
major version links still work
> Adding 7.3.1

- user/languages/community-supported-languages.md
See https://github.com/travis-ci/travis-build/pull/729
> Document version-based deployment

- _includes/sidebar.html
- assets/javascripts/main.js
- assets/stylesheets/_sidebar.sass
hey there @plaindocs 
I did a little scroll thing for sidebar. Is that how you meant it?
Also, I toyed around with some styles. What do you think about this for the navigation? The blue gets quite heavy imo. But this is just an idea:
> sidebar tweaks

- user/caching.md
Corresponds to https://github.com/travis-ci/travis-build/pull/706
> Document how caches are used in a build matrix

- user/languages/php.md
See https://github.com/travis-ci/travis-build/pull/733
> Explain HHVM versions

- user/cron-jobs.md
This has come up several times in support requests, might as well document it?!
> Add cron detection documentation

- _data/xcodes.yml
Xcode 8 Beta `8S128d`
- https://developer.apple.com/xcode/
> Adding details for Xcode 8 Beta (initial release)

- assets/stylesheets/_utils.sass
- user/build-environment-updates.md
Hey @plaindocs!
I think the problem was that the class that was used for the list didn't have the list styles. I created a new class that does. 
I also added the title of the posts you're using in the lists as title attributes to make them a bit more descriptive. Let me know what you think.
> Fix generated link list, close #623

- user/languages/elixir.md
See https://github.com/travis-ci/travis-ci/issues/6130
> Document default command for Elixir 1.3.0 and up

- user/deployment/s3.md
Added docs for https://github.com/travis-ci/dpl/pull/458.
> Add default_text_charset to s3 docs

- user/languages/javascript-with-nodejs.md
Fixed indent and other suggestions made as per [https://github.com/travis-ci/docs-travis-ci-com/pull/624](https://github.com/travis-ci/docs-travis-ci-com/pull/624) .
> Fix on indenting and show comments on the steps we are doing 

- user/environment-variables.md
> Added TRAVIS_EVENT_TYPE

- user/firefox.md
This commit corresponds to https://github.com/travis-ci/travis-build/pull/769
> Document Firefox addon for OS X builds

- _data/xcodes.yml
- This update includes Xcode 8b2
- It also adds
- `swiftlint`
- `cmake`
> Xcode8b2 update

- user/languages/java.md
Documentation for the changes introduced in travis-ci/travis-build#757
> Document travis-ci/travis-build#757

- user/languages/ruby.md
Resolves https://github.com/travis-ci/travis-ci/issues/6266
> Document how BUNDLE_GEMFILE is defined

- user/deployment/script.md
Closes https://github.com/travis-ci/travis-ci/issues/5205
> Explain deployment is done via Ruby 1.9.3

- user/languages/r.md
After [this issue](https://github.com/travis-ci/travis-ci/issues/6297#issuecomment-232399810) and the words of @jimhester
> Added documentation

- user/trusty-ci-environment.md
As per https://github.com/travis-ci/travis-ci/issues/5948
> MongoDB is not available on stable Trusty image

- user/ip-addresses.md
> Replace whitelist terminology with safelist

- user/languages/objective-c.md
See [this issue](https://github.com/travis-ci/travis-ci/issues/5694)
> Include `bundle` in install for objective-c

- user/languages/clojure.md
Corresponds to https://github.com/travis-ci/travis-build/pull/808.
> Document how to update leiningen on the fly

- user/browserstack.md
Changes,
* added link to BrowserStackLocal binary.
* simplified language for explanation of forcelocal binary option.
> Additional review comments for BrowserStack add-on

- user/languages/php.md
atoum PHAR is no longer the best way to use it. This is better to grab it through Composer instead.
> Prefer to use atoum through Composer

- user/database-setup.md
This goes with https://github.com/travis-ci/travis-build/pull/676.
> Add RethinkDB addon to docs

- user/environment-variables.md
Fixes 
#698 
Does not yet fix 
#691
> How do environment variables actually work. WIP

- user/languages/android.md
The script is already fixed.
See: https://github.com/pestrada/android-tdd-playground/blob/master/.travis.yml
> remove warning text

- user/common-build-problems.md
> Correct negation

- user/languages/php.md
Simple spelling fix for the documentation.
> Fix typo in "aliases"

- user/languages/csharp.md
> Document .NET Core support.

- user/environment-variables.md
See https://github.com/travis-ci/travis-build/pull/848
> Document TRAVIS_PULL_REQUEST_* variables

- _data/xcodes.yml
- user/common-build-problems.md
- user/docker.md
- user/languages/objective-c.md
This PR will: 
- update OS X default messages to point to XCode 7.3
- normalize the OS X Environment table
> update OS X default messages

- _data/snippets.yml
- user/notifications.md
> Add template to slack notiications

- user/sourceclear.md
The login link redirects to app.sourceclear, fixed this to use the appropriate link
> Fixed the login link

- user/common-build-problems.md
Fix  #768 and rewrite while I'm there.
> Fix default retries

- STYLE.md
> First steps towards adding a style guide for the docs

- user/ci-environment.md
This will specify that caching is available in all infrastructures and adds a clarification to the infras list.
> CI environment quick updates

- user/deployment/azure-web-apps.md
Just adding some missing documentation.
Here's where slots are implemented in [travis-ci/dpl](https://github.com/travis-ci/dpl):
https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/azure_webapps.rb#L9
> Add documentation for azure slots

- user/caching.md
To correspond to https://github.com/travis-ci/travis-ci/issues/3817
> Update cache searching logic

- user/caching.md
> Fix typo in caching page

- user/languages/r.md
Following up on https://github.com/travis-ci/travis-ci/issues/6504 with @jimhester & @craigcitro
> a few notes on packrat

- user/common-build-problems.md
> Delete this old link

- user/ci-environment.md
- The content now matches the table
- Reflects the current default, `sudo: required`
> Update the virtualization environments section

- _data/xcodes.yml
> Add xcode8.1 image information.

- user/caching.md
- user/languages/javascript-with-nodejs.md
To correspond with https://github.com/travis-ci/travis-build/pull/895
> Document yarn support

- index.html
- user/customizing-the-build.md
Fix for #823 @anarosas please review and merge.
> Add note about Mercurial

- user/database-setup.md
> Update MySQL docs wrt Trusty

- user/languages/go.md
Related to https://github.com/travis-ci/gimme/issues/69
> Document golang version behavior around use of `x`

- user/languages/go.md
> Modify language around golang `x` support

- slate/source/index.md
Related to: https://github.com/travis-pro/team-teal/issues/1536
> Update /repos endpoint documentation

- user/notifications.md
> Add slack notification config example

- user/notifications.md
added a line to permit the code block to render correctly.
> fix code block formatting

- user/customizing-the-build.md
as discovered in travis-ci/travis-ci/issues/6396
> document before_cache in stages

- user/apps.md
Will check back in a week if it should be returned
> Remove  https://ducksboard.com link

- user/customizing-the-build.md
https://github.com/travis-ci/travis-gatekeeper/pull/109
> Document the new matrix limit

- user/customizing-the-build.md
> add "currently"

- user/sonarqube.md
Direct link to Repository Settings for saving SONAR_TOKEN
for page https://docs.travis-ci.com/user/sonarqube/
> Improve SonarQube set-up docs

- user/caching.md
- user/languages/javascript-with-nodejs.md
To correspond with https://github.com/travis-ci/travis-build/pull/920
> Update yarn cache location

- user/environment-variables.md
Corresponds to https://github.com/travis-ci/travis-build/pull/927
> Document TRAVIS_PULL_REQUEST_SLUG

- user/languages/objective-c.md
> Make sure objective-c shows up in search for swift

- user/deployment/launchpad.md
See : https://answers.launchpad.net/launchpad/+question/443697
> Update launchpad deployment page

- user/database-setup.md
- user/installing-dependencies.md
- user/languages/android.md
- user/languages/csharp.md
- user/languages/d.md
- user/languages/elixir.md
- user/multi-os.md
- user/triggering-builds.md
- Elixir Language
- Triggering builds through the API
- Multi OS support
- APT Addon
- updates PostgreSQL versions availability in existing xcode images
> Update BETA sections

- user/languages/community-supported-languages.md
@BanzaiMan Please have a quick look at this, and if you're happy with it merge into your branch and that branch into the docs.
> Edits for clarity.

- user/common-build-problems.md
Resolves https://github.com/travis-ci/travis-ci/issues/7151.
> Elaborate on `travis_wait`

- user/languages/csharp.md
> Fixed Mark down issue on C# page

- user/deployment/s3.md
Fixing small indentation glitch in S3 documentation.
> minor typographical fix (indentation)

- user/languages/r.md
Fixes https://github.com/travis-ci/travis-ci/issues/7246
> Cache the src and lib packrat directories only

- user/deployment/releases.md
Resolves https://github.com/travis-ci/travis-ci/issues/2457
> For GitHub Releases, show example with encrypted API key

- user/customizing-the-build.md
See https://github.com/travis-ci/travis-ci/issues/3670#issuecomment-275720440
for extra information
> Document how matrix.inclue works with matrix expansion

- user/languages/haxe.md
Re https://github.com/travis-ci/travis-build/pull/949
> update haxe default version to 3.4.0

- slate/source/index.md
Could you please verify this small fix, @plaindocs? :)
Thank you!
> Typo in the "Making Requests" section of the API Docs

- user/speeding-up-the-build.md
Change optimise to optimize while we're here to be consistent with the
rest of the file.
> Add notes running parallel make builds

- user/languages/javascript-with-nodejs.md
This simplifies Nodejs versions a bit, maybe too much. Re #940 
Maybe some support people could give me some feedback? I'm happy to shift things back around if this is a bit drastic.
CC @MariadeAnton @lislis @BanzaiMan
> Tweak nodejs re version numbers

- user/migrating-from-legacy.md
I found this page when helping a customer and found the section on the resources to be a bit misleading about the memory in our current container based infrastructure.
> update our legacy migration information

- user/languages/r.md
This is just an additional explanation to make sure newbies like myself don't stumble over this.
This is in relation to [this comment](https://github.com/hadley/devtools/issues/944#issuecomment-278013085) and @jimhester's response.
> Remotes deps also have to be called in Imports: and friends

- user/uploading-artifacts.md
i.e. between the `after_success` and `after_script`.
> Added details about when the artifacts are uploaded

- user/languages/elixir.md
Based on https://gist.github.com/BanzaiMan/3e6370cc0a1991d2d3c9
> Elixir: info on handling different OTP versions

- user/languages/dart.md
Reverts travis-ci/docs-travis-ci-com#980
> Revert "Add Dart documentation for new features."

- user/deployment.md
Just correcting a small typo.
Thank you all for running such a great service!
> Add missing colon to yml example

- user/ci-environment.md
@iriberri →  👀  please? Thank you! 💃
> add container-based trusty to the virtualization environments table

- user/languages/python.md
(Can possibly be attributed to copy-paste from
docs/user/build-configuration.md back then.)
> python.md: s/DB/ENV

- user/languages/php.md
To go with https://github.com/travis-ci/travis-build/pull/991 (& https://github.com/travis-ci/travis-build/pull/985), to explain https://github.com/travis-ci/travis-ci/issues/7226.
> Explain `phpunit` discovery process

- user/languages/csharp.md
We can close a bunch of old issues with this:
Fixes https://github.com/travis-ci/travis-ci/issues/7301
Fixes https://github.com/travis-ci/travis-ci/issues/7255
Fixes https://github.com/travis-ci/travis-ci/issues/7026
Fixes https://github.com/travis-ci/travis-ci/issues/4663
This one was done a while ago:
Fixes https://github.com/travis-ci/travis-ci/issues/5189
@BanzaiMan 
/cc @Joshua-Anderson @nterry
> Update C# docs with latest .NET Core info

- user/deployment/elasticbeanstalk.md
* Move `bucket_name` to the required options
* Clarify what `zip_file` does
> Elastic Beanstalk: Some adjustments

- user/sonarqube.md
@BanzaiMan I finally took the time to update the page to document the newly introduced `organization` parameter.
(cc @dbmeneses)
> Document the organization parameter for the SonarQube add-on.

- user/common-build-problems.md
- user/customizing-the-build.md
- user/database-setup.md
- user/deployment/bluemixcloudfoundry.md
- user/deployment/firebase.md
- user/deployment/testfairy.md
- user/environment-variables.md
- user/notifications.md
> Prism JS uses bash not sh

- user/database-setup.md
- user/trusty-ci-environment.md
Fix for #966
@cotsog @MariadeAnton
> Elastic on Trusty

- user/environment-variables.md
Added a note to fix #971
Clarified some of the other variables.
@MariadeAnton
> Add note about git tags

- user/languages/rust.md
To correspond to https://github.com/travis-ci/travis-build/pull/993
> Update Rust doc

- user/languages/haxe.md
Re: https://github.com/travis-ci/travis-build/pull/996
> update haxe default version to 3.4.2

- user/languages/javascript-with-nodejs.md
To correspond to
https://github.com/travis-ci/travis-build/pull/989
https://github.com/travis-ci/travis-build/pull/997
> Tweaks for recent `yarn` updates

- user/languages/javascript-with-nodejs.md
It was reverted in https://github.com/travis-ci/travis-build/pull/1000
> Remove --frozen-lockfile

- user/caching.md
> Clarify path for ccache

- user/languages/dart.md
See #980 for the previous discussion.
> Add Dart documentation for new features

- user/deployment/npm.md
Fixes https://github.com/travis-ci/travis-ci/issues/7506
> Email is required for all NPM versions

- user/languages/csharp.md
Fixes https://github.com/travis-ci/travis-ci/issues/7610
> C#: add note about using dist:trusty for .NET Core

- user/languages/android.md
As mentioned here:
- https://github.com/travis-ci/travis-ci/issues/6555
- https://github.com/travis-ci/travis-ci/issues/7110
- http://stackoverflow.com/questions/38865798/cant-build-project-with-travis-ci-and-android
Swapping those two lines does fix the issue.
> Putting 'tools' command before the 'platform-tools' command

- user/notifications.md
Added hook verification in golang
> Added Golang Webhook Verification

- _data/snippets.yml
- user/cron-jobs.md
- user/triggering-builds.md
* Does what it says
* I also fixed a broken merge, so an extra set of eyes on the final page would be awesome
* I'm slightly concerned about the findability of the API issue, but we can revisit that
> Document status update limit on GitHub

- user/installing-dependencies.md
As discussed in https://github.com/travis-ci/travis-ci/issues/7647
Just something I clobbered together on my phone at 4am lol. Feel free to suggest improvements.
> Document installing dependencies on multiple OS

- user/deployment/releases.md
Add section for further configuration
> releases.md: Further configuration

- _data/xcodes.yml
We are keeping this image for the time being.
> Removed Xcode 6.4 image deprecation note

- user/firefox.md
To correspond to https://github.com/travis-ci/travis-build/pull/1036.
> Add blurb about unbranded Firefox support

- user/customizing-the-build.md
Related to travis-ci/travis-build#1038
> Add customization section about `git.lfs_skip_smudge`

- user/database-setup.md
Fixes a mispelling in database-setup.md
> Fixing typo

- user/languages/r.md
Motivated by https://github.com/travis-ci/travis-ci/issues/7756.
PTAL @jimhester
> Add a source pointer to the R docs.

- user/build-stages.md
Closes https://github.com/travis-ci/travis-ci/issues/7753
> Add explicit statement about data storage in Build Stages

- _includes/sidebar.html
- user/chrome.md
- user/gui-and-headless-browsers.md
To correspond to https://github.com/travis-ci/travis-build/pull/1041.
> Add documentation on Google Chrome addon

- user/installing-dependencies.md
- user/osx-ci-environment.md
To encourage less to run it, as it can add a significant amount
of time to the build.
> Add note on `brew update`

- user/languages/android.md
Opening this PR with a first proposal to add the Android 25 installation instructions to the docs. Please, feel free to add your commits here.
Any suggestions/recommendations, @MariadeAnton?
> [Android ] Using the latest sdk platform tools

- user/caching.md
Closes https://github.com/travis-ci/travis-ci/issues/7527.
> Document the effect of overriding `install` on `cache` directives

- user/customizing-the-build.md
> Mention git options

- user/deployment/npm.md
These are the 3 most common errors I encounter when using Travis with npm, which generally take me a half hour to solve each time, because I forget the solutions. I figure the world would benefit from having those solutions documented here in the official Travis docs.
(previously discussed in https://github.com/travis-ci/travis-ci/issues/7005)
> Add Troubleshooting section with solutions to common errors

- user/deployment/script.md
> Remove explicit version

- user/encryption-keys.md
Adds a note about the `--add` flag to automatically add the secure token to `travis.yml`
> Describe --add flag

- user/languages/javascript-with-nodejs.md
gulp recommends using gulp-cli: https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md
> Use gulp-cli instead of gulp

- user/caching.md
- user/chrome.md
- user/ci-environment.md
- user/customizing-the-build.md
- user/database-setup.md
- user/getting-started.md
- user/installing-dependencies.md
- user/languages/android.md
- user/languages/clojure.md
- user/languages/csharp.md
- user/languages/erlang.md
- user/languages/go.md
- user/languages/groovy.md
- user/languages/haskell.md
- user/languages/java.md
- user/languages/perl.md
- user/languages/perl6.md
- user/languages/php.md
- user/languages/python.md
- user/languages/scala.md
- user/notifications.md
As pointed out in #1117 
We'll switch over to macos in the future.
> Be consistent on OS X

- user/languages/java.md
> small typo corrected

- user/deployment/pypi.md
Fix for #1059 on https://github.com/travis-ci/docs-travis-ci-com/compare/sw-pypi?expand=1#diff-f522233148651d3b9422d7c90d555ac3R27
And some minor text and heading tweaks while I was there.
@iriberri @joepvd take a look if you fancy.
> Warn about encryption / character issue

- user/common-build-problems.md
- user/installing-dependencies.md
Fixes #1246
Also fixes redirected link on the installing dependencies page.
Thanks to @iriberri for the pointer.
> Mention how to install locales using apt addon

- user/docker.md
You can install it from the Ubuntu APT repo (package name = `docker-engine`) AND from the Docker APT repo (package-name = `docker-ce` or `docker-ee`).
> Documented how to install Docker from the Docker APT repo

- user/best-practices-security.md
Just spotted this typo, so here's the fix! :)
> Fix typo in double Travis CI [security recommendations]

- user/caching.md
> Prepend, rather than append the ccache folder, so it gets found first

- assets/stylesheets/_layout.sass
> remove superfluous padding

- user/deployment/releases.md
https://github.com/travis-ci/travis-ci/issues/7624#issuecomment-294938921
@BanzaiMan I've added your comment to docs.
> Document option passing to Octokit

- user/sonarcloud.md
The filename + redirect in #1262 really confuses Jekyll
> Why is the redirect causing problems?

- user/gui-and-headless-browsers.md
Fixes https://github.com/travis-ci/travis-ci/issues/7968
/cc @BanzaiMan
> Background headless chrome in examples.

- user/deployment/pages.md
> Update pages.md, fixes a couple of typos

- _data/xcodes.yml
Xcode 9 beta 2 information
```
$ xcodebuild -version
Xcode 9.0
Build version 9M137d
```
> Xcode 9beta2 information

- user/installing-dependencies.md
Snaps are the new packaging and delivery system developed by Ubuntu.
> Add a section about installing snap packages

- user/travis-pro.md
@aakritigupta how does this look?
> How to make a repo public

- _includes/footer.html
- imprint.md
> Put this back where you found it Sam

- user/build-stages/share-files-s3.md
Copy stage descriptions from user/build-stages.md.
> Fix stage descriptions for "Share files via S3"

- assets/stylesheets/_ataglance.sass
- assets/stylesheets/_base.sass
- assets/stylesheets/main.sass
- user/languages/ruby.md
> style at a glance box

- _includes/sidebar.html
- user/precise-to-trusty-migration-guide.md
Mainly to get a URL to send to our customers
> First cut of the Precise => Trusty migration guide

- _data/xcodes.yml
Updating version for `xcode9` to beta 4
> Updating version for `xcode9` to beta 4

- user/deployment.md
> Quick search hack

- user/encrypting-files.md
Works fine for me with WSL. Native Windows does not work.
> Added WSL to alternatives for Windows on file encryption

- user/build-stages.md
> Remove link to build stages feedback issue

- user/database-setup.md
> Update mongodb command

- user/addons.md
- user/gui-and-headless-browsers.md
Looking into the trailing slash issue reported in #1340 and #1336
> Broken links and Trailing slashes

- user/deployment/pages.md
It should be called *force push*, not *push force*. :)
> Fix word order

- assets/stylesheets/_base.sass
> bring balance to the list

- _data/xcodes.yml
Updating to reflect Xcode 9 beta 5
> Updating to reflect Xcode 9 beta 5

- user/reference/overview.md
> Fix OS version at "Build Environment Overview"

- user/languages/android.md
- user/languages/groovy.md
- user/languages/java.md
To correspond to https://github.com/travis-ci/travis-build/pull/1140.
> State Gradle daemon is disabled by default

- _includes/c11-cpp11-and-beyond-and-toolchains.md
Updated per support request: https://secure.helpscout.net/conversation/415785687/58354/?folderId=30784
> update llvm version

- STYLE.md
- user/languages/javascript-with-nodejs.md
- user/reference/precise.md
- user/reference/trusty.md
Move version info into reference
> Node JS updates for Trusty

- user/code-climate.md
so that we can deploy docs changes again!
> Fix CodeClimate links

- user/customizing-the-build.md
- user/reference/osx.md
- user/reference/overview.md
Note: I haven't thoroughly tested; this info has been cobbled together from what clues I could find laying around. If we're not sure this is correct info, let me know and I can test more.
> Document Git LFS

- user/languages/perl6.md
FAO @MariadeAnton @BanzaiMan 
I've added the maintainers as meta data -> I'll ask people to do the same when they update the community pages.
> Add maintainers

- _data/xcodes.yml
Updating to Xcode 9 GM seed: build `9A235`
> Updating to Xcode 9 GM seed

- user/for-beginners.md
"This is where Travis CI is comes in." became "This is where Travis CI comes in."
> Removed unnecessary "is"

- user/getting-started.md
Small changes for readability.
> Improved readability

- _data/xcodes.yml
- Installed Xcode 9 via App Store release
- Did userland updates for:
- homebrew
- rubygems
- ruby motion
- etc
> Updated Xcode 9 image to final release

- user/languages/go.md
> Golang page updates

- user/reference/trusty.md
See https://github.com/travis-ci/travis-ci/issues/8199#issuecomment-327246053
> Show how to use OpenJDK 6 on Trusty

- user/languages/scala.md
- user/reference/precise.md
Links in the summary box depend on the Java language updates in https://github.com/travis-ci/docs-travis-ci-com/pull/1464/files
> Scala language updates

- user/build-environment-updates.md
> reverse file ordering in Build Environment Updates

- user/languages/rust.md
Nothing much to update WRT Trusty.
> Small updates to Rust

- user/languages/haskell.md
Nothing environment specific to change.
> Minimal Haskell updates

- _data/xcodes.yml
Adds Xcode 9.1 beta (Build `9B37`)
> Adding Xcode 9.1

- user/deployment/releases.md
Add a comment about editing the `branch.only` property to match the tag names.
> Update deployment docs

- user/languages/haxe.md
See https://github.com/travis-ci/travis-build/pull/1184
> haxe: set default version to 3.4.3

- user/languages/haxe.md
Re: https://github.com/travis-ci/travis-build/pull/1203/
> haxe: default version is "stable"

- user/build-environment-updates/2017-11-08.md
> Xcode9.1-beta to xcode9.1 GA

- user/docker.md
as mentioned in https://github.com/travis-ci/travis-ci/issues/8181
> add note about using addons to update docker

- user/build-environment-updates.md
- user/build-environment-updates/2014-12-09.md
- user/build-environment-updates/2014-12-16.md
- user/build-environment-updates/2014-12-18.md
- user/build-environment-updates/2014-12-29.md
- user/build-environment-updates/2015-01-07.md
- user/build-environment-updates/2015-02-03.md
- user/build-environment-updates/2015-04-09.md
- user/build-environment-updates/2016-08-24.md
- user/build-environment-updates/2016-11-01.md
- user/build-environment-updates/2016-11-15.md
- user/build-environment-updates/2016-12-01.md
- user/build-environment-updates/2016-12-02.md
- user/build-environment-updates/2016-12-06.md
- user/build-environment-updates/2016-12-08.md
- user/build-environment-updates/2017-05-04.md
- user/build-environment-updates/2017-07-12.md
- user/build-environment-updates/2017-08-17.md
- user/build-environment-updates/2017-09-06.md
- user/build-environment-updates/2017-11-01.md
- user/build-environment-updates/2017-11-08.md
Comes from:  https://github.com/travis-ci/docs-travis-ci-com/issues/1576
_small preview_
> split categories for build env updates per OS

- slate/source/index.md
> delete annotations endpoint from api

- user/enterprise/operations-manual.md
See e.g. http://porkmail.org/era/unix/award.html
cc @schultyy
> Remove useless use of cat

- newsletter/index.html
> We dont use this, send people to the blog instead

- user/customizing-the-build.md
See https://github.com/travis-ci/travis-build/pull/1093
> Document `git.depth: false`

- user/languages/haxe.md
Re. https://github.com/travis-ci/travis-build/pull/1280
> haxe: update neko default version

- user/reference/osx.md
> correct brew bundle issues

- user/build-stages/share-files-s3.md
Resolves https://github.com/travis-ci/docs-travis-ci-com/issues/1612.
> Improve S3-based shared files example

- user/deployment/pages.md
> Add info about new behavior of Pages provider

- user/integration/platformio.md
PlatformIO charges a monthly subscription fee for unit testing.
> Note that PlatformIO is a paid service and not a free program

- _layouts/en.html
> Dont index the button

- user/chrome.md
This explains how to avoid https://github.com/travis-ci/travis-ci/issues/8836.
Closes travis-ci/travis-ci#8836
Closes #1668
> Explain use of chrome on containers

- user/deployment/releases.md
Closes https://github.com/travis-ci/travis-ci/issues/9052.
> Explain GitHub releases advanced options

- user/database-setup.md
Resolves https://github.com/travis-ci/travis-ci/issues/9011.
> Explain use of `pg_config`

- user/encryption-keys.md
See https://github.com/travis-ci/travis-ci/issues/2982
> Clarify encryption scheme using notes from issue 2982

- user/caching.md
Resolves https://github.com/travis-ci/travis-ci/issues/9043.
> Explain cache naming rules re: env vars

- user/conditional-builds-stages-jobs.md
This may help avoid others having [my confusion](https://github.com/travis-ci/beta-features/issues/28#issuecomment-357780305).
> Clarify what the branch attribute means for PRs

- user/database-setup.md
- user/reference/precise.md
- user/reference/trusty.md
Fix for #1605
Fix for #1236
Fix for #702
> Clarify MySQL availabilty

- assets/stylesheets/_base.sass
- user/jwt.md
> Add JWT deprecation warning and .warning class

- user/reference/overview.md
Minor tweaks to networking info. Closes #662
> Make IPv6 availability more clear

- _data/xcodes.yml
- user/build-environment-updates/2018-02-07.md
This includes new sdks/simulators and userland updates.
> xcode9.3beta release for docs

- _data/xcodes.yml
> Corrects xcode9.3 image name to beta

- user/gui-and-headless-browsers.md
> Document a simpler xvfb setup

- user/languages/python.md
Resolves https://github.com/travis-ci/travis-ci/issues/9206
> Update Python & PyPy version

- user/environment-variables.md
To correspond to https://github.com/travis-ci/travis-build/pull/1309.
> Document TRAVIS_OSX_IMAGE

- STYLE.md
- _data/snippets.yml
- user/cron-jobs.md
- user/customizing-the-build.md
- user/environment-variables.md
- user/web-ui.md
Start to address #538 
Will close #1370
> Intial list of web ui settings to document

- user/pull-requests.md
Attempt to close  #1516 
Going to add Build PRs and Pushes info in #1685
> Yak shaving PR text

- user/languages/python.md
See https://github.com/travis-ci/travis-ci/issues/9069 for context.
> Add note on `3.7-dev` and up for Trusty

- user/environment-variables.md
Resolves https://github.com/travis-ci/docs-travis-ci-com/issues/508.
> Re-word how TRAVIS_TEST_RESULT is set

- user/uploading-artifacts.md
Resolves https://github.com/travis-ci/docs-travis-ci-com/issues/456.
> Clarify artifacts' S3 upload paths

- user/languages/go.md
See https://github.com/travis-ci/travis-build/pull/1310#discussion_r169568253 for context.
> Use strings in Go version examples

- user/docker.md
Address the issue raised in: https://github.com/travis-ci/docs-travis-ci-com/pull/597#issuecomment-367693389
> Make sure you don't push for PRs

- user/enterprise/build-images.md
This PR updates the "Custom Build images" page with information about our Trusty build environment.
Resolves #1643
> [Enterprise] Custom Docker images for Trusty build environment

- user/languages/objective-c.md
- user/reference/osx.md
> Remove Pre release note

- user/environment-variables.md
> document newly introduced TRAVIS_BUILD_STAGE_NAME env var

- user/deployment/s3.md
To correspond to https://github.com/travis-ci/dpl/pull/712.
> Explain S3's endpoint key

- user/customizing-the-build.md
> Link to PR builds

- user/conditional-builds-stages-jobs.md
@svenfuchs @DrTorte could you take a look?
There is one place where your expertise is needed.
Thanks!
> Add workaround for RHS fns

- user/common-build-problems.md
- user/customizing-the-build.md
> Document set e

- user/reference/overview.md
> Update macOS hostname for worker info build logs

- user/open-source-on-travis-ci-com.md
[We talked about this in #support questions](https://travisci.slack.com/archives/C0E7ZS68Y/p1526058155000037). Made changes in the saved replies but thought I'd update this as well.
> Add note about build settings not being migrated either

- user/customizing-the-build.md
Fixes #1831 
I'm reluctant to put this in the Getting Started guide, because I'm fairly confident that 99% of people reading the docs aren't going to know or care what version of yaml they are using.  But happy to discuss @BanzaiMan @Lin-Buo-Ren ?
> Specify YAML version

- imprint.md
- Add data protection officer to imprint
> Update Imprint with data protection officer

- legal/data-processing-agreement.md
- legal/privacy-policy.md
- Fix links in Privacy Policy and Data Processing Agreement
> Update legal gdpr

- user/enterprise/prerequisites.md
We're now also supporting 16.04
> Fix Ubuntu OS version requirement

- user/common-build-problems.md
> Clarifywhere you can use travis_retry

- user/languages/r.md
PTAL @jimhester @BanzaiMan @jeroen
> Replace craigcitro with Jeroen for R support.

- user/languages/groovy.md
- user/languages/java.md
- user/languages/ruby.md
- user/languages/scala.md
To correspond to https://github.com/travis-ci/travis-build/pull/1347
> Add blurbs about Java 10 and up

- user/getting-started.md
> Admin permissions

- user/running-build-in-debug-mode.md
Added note indicating that public repositories have to be enabled manually.
> Public repository information added

- _data/xcodes.yml
- user/build-environment-updates/2018-06-15.md
- user/reference/osx.md
User documentation for `xcode9.4.1`  🎉 🌮 🍎 🎈
> User documentation updates for xcode9.4.1 release :tada: :apple: 

- user/apps.md
Closes https://github.com/ropenscilabs/travis/issues/65.
>  Add R client to documentation

- user/deployment/hackage.md
@iriberri as discussed via mail
> Hackage deployment from only one GHC version

- user/languages/community-supported-languages.md
> community-supported-languages.md: Fix broken links

- user/database-setup.md
Fixes #1951 
Fixes #1440
Related to travis-ci/travis-ci/issues/6972
> Install PostGIS

- user/customizing-the-build.md
I fixed a typo that might be confusing to newstarters.
> Fixed a typo

- _includes/anchor_headings.html
- _layouts/en.html
Update with fix from allejo/jekyll-anchor-headings/issues/3
> FIx the headinging anchors

- _data/xcodes.yml
- user/reference/osx.md
Fixes https://github.com/travis-ci/docs-travis-ci-com/issues/1548
> Add xcode build number

- user/reference/overview.md
- remove bursted from cores
- correct file system for containers
> Correct virtualization environment overview

- user/deployment/firebase.md
Removed unnecessary "application" from first paragraph.
> Update firebase.md to improve readability.

- user/languages/julia.md
cc: @travis-ci/julia-maintainers
> Update julia docs

- user/languages/php.md
see https://github.com/travis-ci/travis-ci/issues/8968
> Fix php-fpm example

- user/database-setup.md
> Fixed: mysql_upgrade password error

- user/deployment/pypi.md
See https://github.com/travis-ci/travis-ci/issues/10051
> Clarifying where to place the password

- user/running-build-in-debug-mode.md
See https://github.com/travis-ci/docs-travis-ci-com/issues/1907 for motivation.
> Suggest `nvm install` for Node.js debug builds

- user/languages/php.md
Resolves https://github.com/travis-ci/travis-ci/issues/7993
> Drop pyrus

- user/reference/overview.md
I fixed come links in [Build Environment Overview](https://docs.travis-ci.com/user/reference/overview/)
> fixed some links on Build Environment Overview

- user/reference/overview.md
since it is going away and the current default is in transition
> Remove mention of a container-based Linux default

- user/docker.md
Hello!
I think that the commit is self-descriptive :relaxed:
> Remove irrelevant tag from the output

- user/open-source-on-travis-ci-com.md
Reverts travis-ci/docs-travis-ci-com#1883
> Revert "Update open-source-on-travis-ci-com.md"

- user/reference/trusty.md
Fixes /travis-ci/travis-ci/issues/7939
> Link to generic and minimal from Trusty

- user/open-source-on-travis-ci-com.md
This is where I'm merging #1883 into the correct branch... :(
> Update open-source-on-travis-ci-com.md (#1883)

- user/languages/android.md
Included example `travis.yml` for Ionic based project for Hybrid mobile application.
Uses tagged commit to manage GitHub releases.
Signed-off-by: nutannivate <nutannivate@gmail.com>
> Ionic Cordova Example

- _config.yml
- slate/source/index.md
- user/installing-dependencies.md
- user/migrating-from-legacy.md
Updated version to replace #1077
> Whitelist -> safelist

- user/pull-requests.md
Capitalization of fragment URLs has changed
> Fix broken links

- user/caching.md
- user/languages/javascript-with-nodejs.md
To correspond to https://github.com/travis-ci/travis-build/pull/1551.
> Document smarter `cache: npm`

- user/reference/trusty.md
- user/reference/xenial.md
It also updates the default infra redirect to trusty
> * Several xenial updates for consistency

- user/ip-addresses.md
refs https://github.com/travis-ci/reliability/issues/217
> add mailchimp announcement form for ip address changes

- user/reference/overview.md
- user/reference/windows.md
> Fix windows version

- user/languages/c.md
- user/languages/cpp.md
doc PR for travis-ci/travis-build#1564
> Document that compiler option sets CC_FOR_BUILD

- user/build-environment-updates/2014-12-09.md
- user/build-environment-updates/2014-12-16.md
- user/build-environment-updates/2014-12-18.md
- user/build-environment-updates/2014-12-29.md
- user/build-environment-updates/2015-01-07.md
- user/build-environment-updates/2015-02-03.md
- user/build-environment-updates/2015-04-09.md
- user/build-environment-updates/2016-08-24.md
- user/build-environment-updates/2016-11-01.md
- user/build-environment-updates/2016-11-15.md
- user/build-environment-updates/2016-12-01.md
- user/build-environment-updates/2016-12-02.md
- user/build-environment-updates/2016-12-06.md
- user/build-environment-updates/2016-12-08.md
- user/build-environment-updates/2017-05-04.md
- user/build-environment-updates/2017-07-12.md
- user/build-environment-updates/2017-08-17.md
- user/build-environment-updates/2017-09-06.md
- user/build-environment-updates/2017-11-01.md
- user/build-environment-updates/2017-11-08.md
- user/build-environment-updates/2017-12-12.md
- user/build-environment-updates/2018-02-07.md
- user/build-environment-updates/2018-04-09.md
- user/build-environment-updates/2018-06-15.md
- user/build-environment-updates/2018-07-31.md
- user/build-environment-updates/2018-09-05.md
- user/build-environment-updates/2018-09-13.md
- user/build-environment-updates/2018-11-01.md
Hey @mjm @Lyoness @cotsog @bogdanap 
Using these levels of heading displays slightly nicer with with the in page toc. 
Don't think these changes should break anything. :-)
> Fix headings for in-page TOC

- user/deployment/anynines.md
- user/deployment/bluemixcloudfoundry.md
- user/deployment/cloudfoundry.md
Reference: https://github.com/travis-ci/dpl/pull/831
> Add CloudFoundry app_name

- assets/stylesheets/_layout.sass
- assets/stylesheets/prism.scss
I haven’t thoroughly examined the effects of this, it’s
specific to a problem in #2147.
> Change inline files to not have absolute headers

- user/encryption-keys.md
Hello,
It took me two hours to find out why my credentials for PyPI were not working. I believe this information should be here somewhere.
Let me know if you want me to change something, or feel free to change as you wish.
Thanks.
> Mention --com in encryption-keys doc

- user/languages/android.md
- user/languages/groovy.md
- user/languages/java.md
> Don't state that Gradle daemon is disabled by default

- README.md
> README.md:grammar (API Docs are generated -updated)

- _data/snippets.yml
To get a link to windows here:
https://docs.travis-ci.com/user/languages/cpp/#what-this-guide-covers
since it should support cpp too
> Add Windows to trusty_note

- user/languages/julia.md
Document verbose build, see https://github.com/travis-ci/travis-build/pull/1615.
cc @ararslan, @simonbyrne
> Julia: Document verbose build

- user/for-beginners.md
@plaindocs Minor update to aid incremental understanding of core concepts.
> Re-order concepts to aid progressive understanding

- user/environment-variables.md
- user/running-build-in-debug-mode.md
As it will be introduced with: https://github.com/travis-ci/travis-build/pull/1621#issuecomment-447065499
cc @BanzaiMan @plaindocs
> Add docs on TRAVIS_DEBUG_MODE env var

- user/open-source-repository-migration.md
Pinging @MariadeAnton, @clekstro and @drogus here :)
> Extend and update beta migration docs

- user/deployment.md
From a support request, it seems we're lacking an example in this page for multiple deployments but using conditions as well.
What do you think, @plaindocs? :) Thanks!
> Add another deployment example with conditions

- user/database-setup.md
> Update Cassandra source

- user/notifications.md
> Mention IRC authentication

- user/languages/go.md
per PR https://github.com/travis-ci/travis-build/pull/1636
> Update golang docs

- user/coveralls.md
Addresses https://travisci.zendesk.com/agent/tickets/4279
cc/ @cotsog
> Update Coveralls doc links

- user/pull-requests.md
@cotsog this is in relation to ZD: 4906.
cc/ @BanzaiMan
> Add some extra language around forks

- user/languages/javascript-with-nodejs.md
> Remove IOJS

- user/reference/xenial.md
Source: https://travis-ci.community/t/please-allow-pypy-to-work-on-xenial/1980
> Tell how to get PyPy.

- user/enterprise/trusty.md
Updated the cURL link to pull installer script. I also updated it for the installation on Travis CI Enterprise 2.1.9+ instructions as well.
> Update installer script URL

- user/common-build-problems.md
@cotsog addresses ZD: 4815, 5208.
> Add note on Sonatype dynamic IP workaround + type of Github token

- legal/refund-policy.md
These updates avoid confusion on the month after by providing automatic pro-rates
> wording updates to match behaviour

- _data/snippets.yml
- user/languages/c.md
- user/languages/clojure.md
- user/languages/cpp.md
- user/languages/elixir.md
- user/languages/erlang.md
- user/languages/go.md
- user/languages/groovy.md
- user/languages/haskell.md
- user/languages/java.md
- user/languages/javascript-with-nodejs.md
- user/languages/perl.md
- user/languages/php.md
- user/languages/python.md
- user/languages/ruby.md
- user/languages/rust.md
- user/languages/scala.md
Revamp of the #2164 since it has been merged then reverted...
note: #2166 is stall for months...
windows supported language list comes from:
https://docs.travis-ci.com/user/reference/windows/#supported-languages
> Update Data snippet again... (Fix #2166)

- user/deployment/pages.md
> fix docs for travis github deploy config property names

- user/common-build-problems.md
Addresses ZD: 5976
cc: @cotsog
> Update common build problems

- user/pull-requests.md
Addresses ZD: 6203
cc: @cotsog
> Update PR page on Draft PR

- user/languages/python.md
@plaindocs Your review please.
> Testing with Python on Linux, macOS, and Windows

- user/build-environment-updates/2019-03-27.md
- user/build-environment-updates/2019-04-11.md
- user/reference/xenial.md
Reverts travis-ci/docs-travis-ci-com#2318
> Update with new Xenial build environment updates

- user/installing-dependencies.md
Based on https://github.com/travis-ci/travis-build/pull/1701
> Update snaps addon instructions

- user/customizing-the-build.md
https://github.com/travis-ci/travis-build/pull/1715
> Disabling git clone

- user/languages/crystal.md
- Info about new support for nightly build 
- Adding Brian as maintainer
> Update Crystal docs

- user/languages/rust.md
To correspond to https://github.com/travis-ci/travis-build/pull/1731.
> Document Rust caching improvements

- user/pull-requests.md
https://changelog.travis-ci.com/draft-pull-requests-support-105121
> update draft PRs docs

- user/encryption-keys.md
And bring it up to date with API V3
Resolves #2327.
> Explain how to obtain pub key on travis-ci.com

- user/job-lifecycle.md
Closes https://github.com/travis-ci/docs-travis-ci-com/issues/2422
> Update job-lifecycle.md: use install: skip

- user/reference/overview.md
> Update reference to Xenial as default

- user/languages/dart.md
@athomas has volunteered to be an owner for the time being.
> Replace myself as a Dart maintainer

- index.html
Addresses https://travisci.zendesk.com/agent/tickets/10544
> Correct typo on `href`

- _data/xcodes.yml
xcodes.yml modified to reflect the Xcode GM Seed 2 release.
> Xcode 11 GM Seed 2

- user/build-matrix.md
> Add another example to matrix.include

- user/notifications.md
To correspond to https://github.com/travis-ci/travis-hub/pull/199.
> Document array config behavior for notifications

- user/languages/android.md
> android.md: Fix typo "explicitely" -> "explicitly"

- Rakefile
Error example: https://travis-ci.com/travis-ci/docs-travis-ci-com/builds/129591228#L424
Solution as per https://stackoverflow.com/questions/2316475/how-do-i-return-early-from-a-rake-task/2316518#2316518
> Fix "unexpected return" in "rake test"

- user/environment-variables.md
Multiple users have had problems encrypting for travis-ci.com using this guide,
The latest in https://travis-ci.community/t/script-cant-find-secure-environment-variable
> Add procedure for travis-ci.com

- user/languages/erlang.md
Like https://github.com/travis-ci/docs-travis-ci-com/pull/2523, but for Erlang.
https://docs-staging-travis-ci-com.herokuapp.com/user/languages/erlang/#otprelease-versions
> Add Erlang version table

- user/multi-cpu-architectures.md
Added section on using docker within LXD incl. `sudo docker` usage examples
> Using docker within LXD

- user/reference/overview.md
Added lxd-arm64 description under Worker information image
> Worker information update

- user/migrate/open-source-repository-migration.md
- badge redirection
- build history migration
- automated beta
- select several repositories at once to migrate
> update migration guide with latest updates

- user/deployment/releases.md
To correspond to https://github.com/travis-ci/dpl/pull/963.
> Enumerate valid GitHub Releases options

- user/customizing-the-build.md
Please take a look.
This adds documentation for travis-ci/travis-build#1779.
/cc @BanzaiMan
> Document core.autocrlf control

- user/languages/nix.md
See https://github.com/travis-ci/travis-build/pull/1804#issuecomment-550015745
> Default Nix version: 2.0.4 -> 2.3.1

- user/reference/xenial.md
Current stable version is 5.0
see: https://staging.travis-ci.com/qa829/qa/jobs/490908#L208
> Default redis version is 5.0

- user/enterprise/upgrading.md
> Add note for Bionic upgrade

- user/multi-cpu-architectures.md
Added IBM Power and Z relevant entries and changes
Added identification section
Extended Security & LXD section
Added huge pages support remark
> Multi CPU Arch - add IBM Power and Z support

- user/languages/python.md
thanks for making it so easy to suggest changes. I love the template for the site.
> simple typo

- user/triggering-builds.md
The current documentation about merge_modes is misleadingly incomplete.
This resolves https://github.com/travis-ci/docs-travis-ci-com/issues/1485
> Improve documentation for merge_modes

- user/build-matrix.md
__Matrix__ is the concept but the yaml key should be __jobs:__.
Also, update some Python version numbers.
> Complete the shift to the "jobs:" key for matrix

- user/languages/ruby.md
This backtick causes builds to fail.
> Remove extraneous backtick

- user/conditions-v1.md
Subj, to give an exact idea of what regex syntax is valid.
> Specify the regex flavor used

- _includes/deploy/tags.md
"like so" instead of "like do"
> fix minor typo in deploy/tags.md

- user/reference/bionic.md
- user/reference/xenial.md
https://travis-ci.community/t/xenial-image-includes-clang-without-llvmgold-support/3522/11
> Document the configuration of custom-installed tools

- legal/terms-of-service.md
Update Terms of Service.
More info here: https://github.com/travis-ci/travis-web/pull/2301 & https://github.com/travis-pro/billing-v2/issues/216
> Update Travis CI terms of service

- .gitignore
- .travis.yml
- bin/dpl
this PR won't work until https://github.com/travis-ci/dpl/pull/1168 is merged
once this PR got merged though we can automatically create PRs for changes in dpl. this would happen in the cron build.
> run dpl git_branch to auto update dpl v2 docs

- user/languages/javascript-with-nodejs.md
See https://github.com/travis-ci/travis-build/pull/1858.
> Document Yarn’s --frozen-lockfile

- user/common-build-problems.md
Could you please review? Thank you ❤️
> case "Build config did not create any jobs" added.

- user/environment-variables.md
Reverts travis-ci/docs-travis-ci-com#2720, due to anchor issues.  Will look over and merge myself at later time.
> Revert "Document the format for environment variables' values"

- user/environment-variables.md
Reverts travis-ci/docs-travis-ci-com#2722
> Revert "Revert "Document the format for environment variables' values""

- user/customizing-the-build.md
As per https://blog.travis-ci.com/2020-03-16-travis-ci-bitbucket-integration
> Bitbucket is supported (BETA)

- .dockerignore
- Dockerfile
Adding a Dockerfile for docs-travis-ci-com, already running on staging.
> Adding Dockerfile

- _data/xcodes.yml
Hey @Cesar, I think I have found why https://travis-ci.com/github/travis-ci/docs-travis-ci-com/builds/160493247 failed.
> update indicate place

- user/github-oauth-scopes.md
.com can host public repositories nowadays, so it needs to be taken into account
See https://github.com/travis-ci/travis.rb/issues/708#issuecomment-620235746
> Adjust headings

- user/running-build-in-debug-mode.md
Depends on https://github.com/travis-ci/travis-build/pull/1905
See https://docs.travis-ci.com/user/running-build-in-debug-mode
> Add instructions on saving debug session output

- user/customizing-the-build.md
To correspond to https://github.com/travis-ci/travis-build/pull/1906.
> Document git.symlinks option

- user/environment-variables.md
Update global variables example to match its description
> Replace matrix key with jobs key

- user/deployment/pypi.md
This will match the lint output:
> Deploy to pypi change user: to username:

- user/common-build-problems.md
- user/private-dependencies.md
Reverts travis-ci/docs-travis-ci-com#2806
> Revert "clone import settings"

- user/build-stages.md
See https://www.dailywritingtips.com/aesthetic-or-aesthetical/
> Fix minor wording issue

- _includes/deploy/before_after_deploy.md
- user/job-lifecycle.md
@BanzaiMan , it turns out this was already stated. Just added some emphasis.
> Emphasize conditions for before/after steps to run

- _data/xcodes.yml
> Adding Xcode 11.6 beta info

- user/trusty-to-xenial-migration-guide.md
Also suggested as in the Zendesk ticket:
https://travisci.zendesk.com/agent/tickets/19064
> added PG workaround with mount point

- user/customizing-the-build.md
Align with https://devguide.python.org/#status-of-python-branches and
https://devguide.python.org/devcycle/#end-of-life-branches
> customizing-the-build: Reasonable Python versions

- user/reference/bionic.md
- user/reference/xenial.md
Updating Xenial and Bionic information following the release of the new images. Please do not merge now :)
Tks!
> Updating Xenial and Bionic information

- _data/xcodes.yml
> Adding Xcode 12 beta 5 info

- user/languages/python.md
This link "https://github.com/twisted/klein/blob/master/.travis.yml" is not found.
> Not Fount URL

- _data/xcodes.yml
> Updating Xcode information

- user/docker.md
Guidance re: https://docs.docker.com/docker-hub/download-rate-limit/
> Add guidance for Docker Rate Limit

- _includes/sidebar.html
- user/billing-faq.md
- user/billing-overview.md
Creating Hosted Billing section in sidebar
Creating Overview doc with explanation
Creating FAQ doc
> Hosted Billing docs

- user/languages/dart.md
Updating to (not so) new Dart language home.
/cc @kevmoo
> update dart link

- user/languages/python.md
> Add note about upcoming pip20.3 defaults

- user/billing-faq.md
- user/billing-overview.md
adding free plan and oss remarks
> Free plan remarks added

- user/common-build-problems.md
Easy navigation and easy reading for others
> Fix broken url in docs

- _data/language-details/archive_definitions.yml
- user/languages/php.md
Show PHP versions in a table instead of confusing list of Ubuntu versions.
> Add PHP versions table

- user/reference/focal.md
After it was found [here](https://travis-ci.com/github/JJ/raku-aulas/builds/210370447)
> Adds support for Perl

- user/reference/bionic.md
Based on [this log](https://travis-ci.com/github/JJ/raku-aulas/builds/210368918)
> Updates info for Perl on Bionic too

- user/reference/xenial.md
> Update information on the installed Perl version

- _data/snippets.yml
Small typo fix to docs-travis-ci-com/_data/snippets.yml
> Fixed a typo in docs

- user/sonarcloud.md
Add an explicit step about activating your repository on Travis, with a link to the tutorial.
> Add activation step to directions

- user/triggering-builds.md
Add information on how to trigger a specific commit with API V3.
This information wasn't available before, so I had to experiment with different parameters to find the solution.
> Add info on how to trigger a specific commit

- user/billing-overview.md
- user/multi-cpu-architectures.md
- user/reference/overview.md
Partner queue solution doc updates
> Partner queue solution doc updates

- _data/snippets.yml
- _data/xcodes.yml
Data retrieved from https://travis-ci.com/github/native-api/test_travis/builds/224435533
> Add xcode 12.4

- _includes/sidebar.html
- user/reference/freebsd.md
> FreeBSD docs fixes

- _data/snippets.yml
The comma splice was bothering me.
> Fixed comma splice.

- user/languages/go.md
The project has switched away from Travis.
> Remove tsuro from examples

- user/reference/bionic.md
> Add Bionic PHP extention section

- user/billing-overview.md
Update of user's documentation (billing-overview.md) for Free Plan with information about 30 days limit.
> Update of billing-overview.md for Free Plan

- user/reference/focal.md
> Update pre-installed jdk versions

- _includes/footer.html
An additional div.status class was created in the css files for [erlang](https://docs.travis-ci.com/user/languages/erlang/) ,[python](https://docs.travis-ci.com/user/languages/python/) and [php](https://docs.travis-ci.com/user/languages/php/) pages.
As both the pages end with a table of archived versions where tablefilter has been used.
Updated the footer.html.
#3078
> Update footer.html to fix the status indicator dot

- user/ip-addresses.md
Changed URL
https://docs.travis-ci.com/user/common-build-problems/#ftpsmtpother-protocol-does-not-work
to
https://docs.travis-ci.com/user/common-build-problems/#ftpsmtpother-protocol-do-not-work
> Change URL

- user/billing-overview.md
Please let me know your thoughts @stan-travis
> Free Plan credits section updated

- _data/snippets.yml
- user/encryption-keys.md
- user/private-dependencies.md
- user/pull-requests.md
Documentation part for the release
> New Git repo settings (sharing secrets with forks)

- user/enterprise.md
- user/enterprise/tcie-3.x-overview.md
* adding link in about
* extending TCIE 3 Overview page by some details
> What's new in 3

- _includes/sidebar.html
- user/build-config-imports.md
- user/hashicorp-vault-integration.md
Please review new page and new updated section
> Hashicorop vault integration docs

- user/reference/xenial.md
Adding update regarding postgre apt packages for Xenial
> Xenial postgre update

- user/billing-overview.md
- user/reference/overview.md
Added GPU Support to the Billing Overview and to the Build Environment Overview pages.
> Gpu support

- user/docker.md
Test Run: https://app.travis-ci.com/github/test-runs-tci/travis-test-builds/builds/266514920
> Docker engine update recipe

- user/billing-overview.md
Need a clear summary on when credits are necessary in concurrent plans (even though premium vm section explained that, it seems some may missed the information)
updated avbailability of coincurrency plans in Travis CI
> First table content updated

- user/browserstack.md
As requested by BrowserStack - adjusted URLs in Travis CI documentation
> Update browserstack.md url traffic identifiers

- Dockerfile
To resolve issue with https://app.travis-ci.com/github/travis-infrastructure/k8s-deploy/builds/268346424#L859-L861
> use explicit bundler version

- user/languages/rust.md
Fixed a couple minor grammar issues in the user/languages/rust.md file.
> Fixed minor grammar issues

- user/billing-faq.md
- user/billing-overview.md
Overview, auto-refill and FAQ docs sections updates
> Docs updates after pricing updates - part 1

- user/billing-overview.md
Updating descritpions for plan types and associated costs
> Update billing overview descriptions

- user/deployment-v2/conditional.md
- user/deployment-v2/custom.md
- user/deployment-v2/providers/azure-web-apps.md
- user/deployment-v2/providers/bintray.md
- user/deployment-v2/providers/boxfuse.md
- user/deployment-v2/providers/chefsupermarket.md
- user/deployment-v2/providers/cloudfiles.md
- user/deployment-v2/providers/codedeploy.md
- user/deployment-v2/providers/datica.md
- user/deployment-v2/providers/elasticbeanstalk.md
- user/deployment-v2/providers/engineyard.md
- user/deployment-v2/providers/firebase.md
- user/deployment-v2/providers/gcs.md
- user/deployment-v2/providers/google-app-engine.md
- user/deployment-v2/providers/heroku.md
- user/deployment-v2/providers/netlify.md
- user/deployment-v2/providers/npm.md
- user/deployment-v2/providers/openshift.md
- user/deployment-v2/providers/opsworks.md
- user/deployment-v2/providers/packagecloud.md
- user/deployment-v2/providers/pages.md
- user/deployment-v2/providers/puppetforge.md
- user/deployment-v2/providers/pypi.md
- user/deployment-v2/providers/releases.md
- user/deployment-v2/providers/rubygems.md
- user/deployment-v2/providers/s3.md
- user/deployment-v2/providers/script.md
- user/deployment-v2/providers/snap.md
- user/deployment-v2/providers/surge.md
Updated titles for Deployment V2 pages
> Heading update v2

- user/languages/android.md
> docs: Update Android build documentation with current distributions and components

- _data/snippets.yml
- user/caching.md
- user/languages/java.md
- user/languages/minimal-and-generic.md
- user/reference/linux.md
- user/reference/noble.md
- user/reference/overview.md
- user/reference/xenial.md
> Adding Ubuntu Noble

- user/billing-faq.md
- user/billing-overview.md
Updated the Billing Overview and FAQ pages as requested in Assembla ticket DU-36
> Du 36/update billing

- _includes/c11-cpp11-and-beyond-and-toolchains.md
- _includes/sidebar.html
> Nrios14 patch 6
