travis-ci/docs-travis-ci-com

user/deployment/npm.md

When you generate a new .npmrc, the _auth key no longer exists. Instead there is a _password key. The _auth property had contained the base64 encoded string composed of username:password. The _password property only contains the base64 encoded password, without the username.
This updates the instructions in a way that works for both versions.

update instructions for getting api key

---

user/build-environment-updates.md
user/build-environment-updates/2015-02-03.md

Some features may be added or dropped, but most of these should go
as planned.
PostgreSQL 9.4 support is still experimental, since we have not had
time to test it extensively; the best way to test it is to let
the world use it!

Announce 2015-02-03 updates

---

user/deployment/s3.md

I've tried to figure out if it is possible to set `Cache-Control` for S3 deploy, finally I've found that it is supported by deploy tool https://github.com/travis-ci/dpl#s3 but not documented.

Deploy S3 - HTTP cache headers

---

user/languages/objective-c.md

From:
> If you are using a workspace instead of a project, use the `xcode_workspace` key in you .travis.yml instead of `xcode_project`.
to
> If you are using a workspace instead of a project, use the `xcode_workspace` key in **your** .travis.yml instead of `xcode_project`.

you -> your

---

user/languages/objective-c.md

Per saucelabs-mac-1.worker.travis-ci.org:travis-mac_osx-1:
```
ERROR: SDK 'iphonesimulator8.0' doesn't exist.  Possible SDKs include: macosx, iphoneos, macosx10.9, macosx10.10, iphonesimulator, iphoneos8.1, iphonesimulator7.1, iphonesimulator8.1, iphonesimulator7.0
```

update list of installed OS X/iOS SDKs

---

user/languages/ruby.md

Maybe you meant 2.0.x?
But actually we're not gonna make any other 2.0 release than 2.0.0, so this doesn't have to be 2.0.x.
Let it just be 2.0.0 here.

Ruby 2.0.c  ->  2.0.0

---

user/database-setup.md

Adding a description of how to make Travis CI wait for the elastic search server to start

Adding elastic search info

---

user/languages/rust.md

The interpretation of the 'rust:' attribute in the .travis.yml
recently changed[1] to support anything rustup.sh supports (through
--spec). This commit updates the documentation to match, including the
example to be something more likely to be useful to a present day rust
user.
[1] https://github.com/travis-ci/travis-build/pull/430/commits
(Jekyll rendering untested due to problems with Jekyll/Ruby gems. I'd rather submit it without rendering it, than not.)

Update rust build instructions: version specification

---

user/languages/ruby.md

Based on [the source code](https://github.com/travis-ci/travis-build/blob/fc9e9d07fbd3464a2a5ca45806d6dd4fa01fea1b/lib/travis/build/script/shared/rvm.rb#L85-L90), it doesn't matter if the version specified in `.ruby-version` is pre-installed on the worker or not, as it is just piped to `rvm use [...] --install --binary --fuzzy`.

Remove note about .ruby-version only being respected if the version is pre-installed

---

user/deployment/packagecloud.md

The "minimal example" was just a tad *too* minimal

user/deployment/packagecloud.md: missing repo name

---

user/ci-environment.md
user/getting-started.md

* A link from the getting started page was broken due to a missing leading
slash
* Minor typos on the CI environment page

Fix typos & correct a link

---

user/languages/r.md

R support in Travis CI currently requires `sudo`, so let's help first-time-users with a more complete basic configuration file.

sudo is required

---

_data/languages.yml
user/languages/perl6.md

This is the documentation to accompany the community-supported Travis build for Perl 6 (see https://github.com/travis-ci/travis-build/pull/415).

Add documentation for Perl 6

---

user/languages/community-supported-languages.md

The pull request cited in the section about how to update the `travis-web`
project for language matrix expansion points to a commit to a file which no
longer exists.  It is thus hard to find the correct file to update.  This
change updates the text to mention the file which currently needs to be
edited in order to add a new language to the list of language configuration
keys, and thus hopefully reduces confusion on the part of the user.

Make clearer how to update the travis-web project for matrix expansion

---

user/customizing-the-build.md

GitHub doesn't advertise `git://` URLs anywhere, and we don't encourage using them.
The preferred protocol for "Public URLs" is HTTPS.
Thanks! :v:

Use https:// (not git://) URLs

---

user/installing-dependencies.md

Added a missing link to "The Build Environment" page.

Add missing link in installing-dependencies.md

---

user/apps.md

Fixes this: ![screenshot](http://i.imgur.com/swL8uQx.png) 
Also figcation and figure were only used in this one place in the file, they've been removed.
http://docs.travis-ci.com/user/apps/#Windows

Fixed syntax error, removed unused tags

---

user/notifications.md

Using commit_message breaks the notification if it contains a newline, so commit_subject is the far more useful key. Document it so people don't have to dive to https://github.com/travis-ci/travis-tasks/blob/master/lib/travis/addons/util/template.rb#L30

Document commit_subject for IRC notifications

---

user/apt.md

As part of investigating https://secure.helpscout.net/conversation/98485511/17130/ I determined that the duplicate nested keys was resulting in the issue and filed https://github.com/travis-ci/travis-yaml/issues/64.
I'm also adding a clarification to the apt page about how to use `sources:` and `packages:` together to hopefully avoid this particular case of confusion in the future

Adding a clarification to the apt page about how to use `sources:` and `packages:` together

---

user/languages/rust.md

Drop an apostrophe to make sure jekyll picks
up the code block.

Fix the Rust versions example

---

_layouts/en.html
user/languages/go.md

Proof of concept for adding metadata to pages in the Jekyll content not the Swiftype user interface.
There is an issue in that the tags are treated as one single tags, not split at the moment, (ie there is only ever ONE tag in the html), but that does not affect the search term inclusion we're using it for.

Using meta tags to add indexing terms to swiftype

---

user/languages/julia.md

for https://github.com/travis-ci/travis-build/pull/487
cc @staticfloat @ninjin
(p.s. Elliot I think it should be possible to go back as far as 0.2.0 on osx workers, is it worth copying 0.2.1 to 0.2-latest in case anyone wants to try that? It won't have `Pkg.test` so the default script won't work, but a few people might find it useful)

Julia versions doc update

---

user/languages/csharp.md

First commit fixes travis-ci/travis-ci#4130.
Second one corrects mentions of the nightly channel which should be the weekly channel (see https://github.com/travis-ci/travis-build/pull/482).

C#: clarify Mono version selection + weekly channel doc fix

---

user/deployment/packagecloud.md

Based on feedback received in https://secure.helpscout.net/conversation/108508480/18429/.

Added precision on what the packagecloud repo name should be.

---

user/uploading-artifacts.md

Hello,
I stumbled around a good bit trying to get artifact upload working and it would have been really helpful to have the documentation mention needing the field ```s3_region```.
Hope this helps someone.

Add s3_region to minimal configuration example

---

user/languages/javascript-with-nodejs.md

Update instructions for building Meteor Packages. Adding `$HOME/.meteor` to PATH gets tests for Meteor Packages to run.

Meteor docs: Add .meteor to path. Allows meteor package tests to run.

---

user/notifications.md

I thought this would make it more helpful for other people like me who put the secure field at the top level alongside the `on_success` / `on_error` / `on_start` flags.

Provide clearer documentation on how to encrypt slack tokens while using on_success, etc.

---

user/languages/go.md

See https://github.com/travis-ci/travis-build/blob/305921ecd5eaf1feb4801cc0ed0b8d1561ab741c/lib/travis/build/script/go.rb#L78 for where it's actually used. :+1:

Fix "go_build" vs "gobuild_args" disparity

---

_data/deployments.yml
user/deployment/azure-web-apps.md

Adds information about the `verbose` option to the Azure Web App provider page. It also adds the small Azure provider to the list of supported providers.
(Should only be merged once https://github.com/travis-ci/dpl/pull/329 is merged)

Azure dpl Provider: `Verbose` option, add to providers list

---

user/migrating-from-legacy.md

Per suggestion from support email, remove unwanted space in mailto: link.

Per suggestion from support email, remove unwanted space in mailto.

---

user/languages/crystal.md

Starting from [0.8.0](https://github.com/manastech/crystal/releases/tag/0.8.0) release Crystal use `shard.yml` file to define dependencies. AFAIK other mentioned behavior haven't been changed. 
/cc @will

Corrected Crystal's filename for dependencies

---

user/build-timeouts.md

This is a fix of a small grammatical error.

Match verb to plural in build-timeouts title

---

user/languages/perl6.md

Use the "installdeps" trick to install all declared dependencies,
instead of a list of hard-coded dependencies

Perl 6 language documentation: more generic dependency installation

---

user/customizing-the-build.md

The notice that using `apt` with `sudo` is not suitable for container-based
environments needs a pointer to what to use instead.
I searched literally for days and finally gave up on using containers.  This needs to be easier to find, especially from the page where you are directed by the dialog box which recommends to use containers instead.

Point to apt plug-in for customizing containers

---

user/docker.md

After [Ubuntu Trusty Beta official roll-out](http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/), docker-compose is now preinstalled.
PS: This new Build Env is awesome, thanks :heart:

The Docker enabled environment now comes with docker-compose preinstalled

---

user/languages/community-supported-languages.md
user/languages/index.md
user/languages/smalltalk.md

We just created the documentation for Smalltalk support in Travis CI since we recognized it is still missing.
See here: [http://docs.travis-ci.com/user/languages/community-supported-languages/#List-of-community-supported-languages](http://docs.travis-ci.com/user/languages/community-supported-languages/#List-of-community-supported-languages)

Created documentation for Smalltalk

---

user/database-setup.md
user/using-postgresql.md

Part of travis-ci/travis-ci/issues/2959 to provide more memory to
instances that don't use mysql and postgresql is to get new builds
to have services: mysql and services: postgresql as part of the
configuration.

mysql and postgresql use services:

---

user/caching.md

The broken screenshot is on http://docs.travis-ci.com/user/caching/
It looks like this currently:
It should look like this:

Fixes a broken screenshot link on the Caching page

---

user/notifications.md

While irc.freenode.org is CNAME for irc.freenode.net, it should never be
used or documented anywhere, because the SSL certificates are valid for
*.freenode.net.
In case someone followed Travis documentation and configured their IRC
client that way, they would get strange errors on freenode's valid SSL
certificates being invalid or worse, think they should be invalid and
blindly accept them.

user/notifications.md: use irc.freenode.net

---

user/caching.md

A customer thought explicit bundler caching was not yet available due to the line *(not yet enabled)*
http://i.nikwakelin.com/823m19p6dj-m29.png
@plaindocs, what do you think?

clarify automatically bundler caching

---

user/multi-os.md

Add a simpler Multi OS example, a mention to matrix.include and leaves the python example using `language: generic` as an extra in the examples
cc/  @plaindocs

add Multi OS simple example

---

user/languages/android.md

`-no-skin` parameter removes the skin. This means that the emulator will be 320x480 pixel widthxheight and 320 density which messes up with most of the tests.
The default skin is 480x800 which is fine for most of the cases. 
`--skin WXGA720` can be used like below to make tests more trusted. This is the best emulator config that is found by default. 
- echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a --skin WXGA720

`-no-skin` is removed from Android docs

---

user/notifications.md

Also, move Hipchat's PR notification bit to the right place.

Explicitly state which notifiers are not triggered by PRs

---

user/languages/php.md
user/speeding-up-the-build.md

XDebug is required for code coverage generation, and has a high impact upon
test performance. Composer recommend disabling XDebug when running composer
(https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer),
and huge benefits can be seen by running phpunit without xdebug enabled.
These changes:
* add information to this effect to the Speeding up the build page; and
* improve organisation of the PHP page to enable direct linking for
disabling PHP extensions in travis.yml.

Add notes to optimise PHP runs by disabling XDebug

---

user/languages/c.md
user/languages/cpp.md

https://github.com/travis-ci/travis-ci/issues/4682 reports
that MPI builds will have a hard time if
CC and CXX are set.
Changing default behavior is not practical, and sneaking around
the user intentions to deal with this special case is wrought
with edge cases.
So we will document, so that users may find it and shape
their builds to their liking.

Note MPI and $CC & $CXX interaction

---

user/github-oauth-scopes.md

We should have private repo scopes as well as open source as per travis-pro/team-sapphire/issues/214
@sinthetix could you take a look at this?

Adding Private GitHub OAuth scopes

---

user/deployment/bintray.md

Hello, I am with JFrog (home of Bintray). There was a small change that was needed to be made for the documentation of the Bintray provider section:
"Removed small documentation mistake about having to use brackets for the excludePattern param in the bintray descriptor example."
We have verified this to be incorrect. There is no need to use brackets for the 'excludePattern' param.
Note - an equivalent PR was submitted to the travis-ci/dpl repository readme file.
Thank you.

Update README.md for the bintray provider

---

api/index.html

Based on the code here: https://github.com/travis-ci/travis-api/blob/master/lib/travis/api/app/endpoint/authorization.rb#L97
The actual parameter is `redirect_uri` instead of `redirect_to`.  This pull request adjusts the documentation to accurately reflect the parameter.

fix redirect_to -> redirect_uri

---

user/caching.md

This corresponds to https://github.com/travis-ci/travis-build/pull/626
The PR above introduces a separate `setup_cache` phase which is
not affected by `install`. This means that even when `install` is overridden,
the special caching directives such as `cache: bundler` and `cache: pip`
will be respected.

Update caching doc to reflect setup_cache phase

---

user/languages/r.md

- Fixes documentation about matrix builds
- examples use lowercase `r`.
- makes the markdown easier to read

Reformat R documentation

---

user/languages/ruby.md

The "Supported Ruby Versions" section claims that "recent" versions of ruby-2.2.x are installed, when in reality only 2.2.0 is and not 2.2.1, 2.2.2, or 2.2.3. I changed that line to clarify that just 2.2.0 is installed.

Clarify which Ruby versions are installed

---

user/customizing-the-build.md

Mac build timeouts are hard set to 50 minutes.
The commit introduces the terms, hard timeout and idle-output timeouts as the
two types of possible timeouts for a job.
This fixes https://github.com/travis-ci/travis-ci/issues/3810

Clarify build timeouts for mac (#3810)

---

user/deployment/codedeploy.md

This documents the feature added by travis-ci/dpl#269, waiting for AWS CodeDeploy deployments to complete.

Document wait-until-deployed for AWS CodeDeploy

---

user/languages/r.md

These changes should be merged after https://github.com/travis-ci/travis-build/pull/683.

Changes to reflect use of the bioconductor version aliases

---

user/languages/javascript-with-nodejs.md

using `stable` for your node version is deprecated now: https://github.com/creationix/nvm#usage
ref: https://github.com/GoogleChrome/lighthouse/pull/85

nodejs: stable keyword is deprecated

---

user/customizing-the-build.md
user/getting-started.md
user/languages/ruby.md

Changes include:
* Removing 1.8.7 and 1.9.2 from the default config since they were end-of-life'd.
* Prioritizing 2.2 over 1.9.3.
* Changing jruby-head to jruby, as per travis-ci/travis-ci/issues/3067.
* Specifying Ruby 2.x instead of 2.x.x.
Since Ruby 2.1.0, [the MRI versioning policy changed to follow Semantic Versioning][1].
Thus, it is better to leave the patch version unspecified as this way the latest patch release will be selected automatically.
This probably deserves to be mentioned in the Ruby documentation but for now I think these changes will do.
[1]:
https://www.ruby-lang.org/en/news/2013/12/21/ruby-version-policy-changes-with-2-1-0/

Update tested Rubies

---

user/encrypting-files.md

Fix the following `gpg` invocation error:
```
gpg: Invalid option "--pass-phrase-fd"
```
As per the https://www.gnupg.org/documentation/manpage.html, there is no dash (- present in the command line switch name.

Remove extra dash in the command line switch.

---

user/database-setup.md

I think this line was accidentally deleted. Restored it, along with command to restart ElasticSearch to start using new version.

Command to install specific ElasticSearch version

---

user/deployment.md
user/deployment/cloudfiles.md
user/deployment/releases.md

consistent use of 'api_key' in examples

---

user/languages/php.md

It is not available for PHP 5.5 or 5.6.
Fixes https://github.com/travis-ci/travis-ci/issues/5618

Drop mention of apc

---

user/osx-ci-environment.md

As [reported by @solarce](https://travisci.slack.com/archives/teal/p1462462487001036
), Firefox was showing the text of each line item beneath its bullet. For example:
This unsightly template formation seems required to prevent the generated whitespace being interpreted as paragraphs in Markdown. See this discussion:
https://github.com/Shopify/liquid/issues/216
Haml has `<` and `>` to handle this kind of thing, hopefully eventually Liquid will get something like it.

Remove whitespace around list items

---

user/languages/haxe.md

See https://github.com/travis-ci/travis-build/pull/730

default neko version for "language: haxe" is now 2.1.0

---

user/environment-variables.md

This commit removes a top-level list for information that is not
appropriate for a list. This also helps to prevent rendering
weirdness with multiple unordered lists where one was
intended. It also adds an initial global sentence describing the
main idea of the lead section.

Clarifies lead of environment variables docs

---

user/installing-dependencies.md

With https://github.com/travis-ci/travis-build/pull/723,
`apt` addon can install any package, and add any repository
on `sudo`-enabled infrastructure.

Update `apt` addon documentation

---

user/languages/clojure.md

I love testing my Clojure projects with [Speclj](https://github.com/slagyr/speclj), and I noticed that it's not included here yet. I've had success using it with Travis, so I've added a few lines to the Clojure documentation.

Add instructions for testing with Speclj in Clojure

---

user/installing-dependencies.md

The example given in the docs causes a build failure because the working directory has been changed after installing a source dependency.  Using `pushd` and `popd` to restore the original working dir fixes the problem.

Use pushd/popd when compiling source dependency to preserve working dir

---

user/languages/javascript-with-nodejs.md

llvm.org has pulled APT repos (http://lists.llvm.org/pipermail/llvm-foundation/2016-May/000020.html)
so using this snippet causes the bild to fail.
See https://github.com/travis-ci/travis-ci/issues/6120

Remove mention of llvm in Node.js doc

---

user/docker.md

* Add after_success and branch examples
* Remove a comment

Add after_success and branch examples (#1)

---

api/index.html

References:
- https://github.com/travis-ci/travis-api/blob/master/lib/travis/api/v2/http/build.rb#L65-L78
- https://github.com/travis-ci/travis-api/blob/master/lib/travis/api/v2/http/job.rb#L27-L41
- https://github.com/travis-ci/travis-api/blob/master/lib/travis/api/v2/http/jobs.rb#L26-L39

Job entities don't contain duration

---

user/languages/javascript-with-nodejs.md

There're some release versions for Node.js v4, v5, and v6.
See: https://nodejs.org/en/download/releases/

Correct Node.js versions

---

user/languages/java.md

closes #609, kudos to @himikof for finding the issue and suggesting the initial fix. 
This is basically a guess work based on the experimental data (see the builds for [this branch]). Perhaps some gradle expert can provide more info/more appropriate solution?
[this branch]: https://github.com/intellij-rust/intellij-rust/tree/travis-cache

update gradle caching instructions

---

user/languages/php.md

These have been available for a while, but remained undocumented.
There has been at least one report of memcached working, so
I suppose it is time to publicize.

Update PHP 7 extensions list

---

user/languages/java.md
user/osx-ci-environment.md

Created a short section on the osx environment page regarding jdk_switcher not being available, to serve in addition to the note on the java languages page

added section to osx build environment only on jdk_switcher

---

user/deployment/azure-web-apps.md

It's important to note that you must have local git deployment enabled for this provider to work. This is not enabled by default, so you must enable it using the instructions provided in the link or the deployment will fail.

Clarify local git deployment method in Azure Web Apps deployment documentation

---

user/caching.md

This is a minor change, but I always end up Googling how to cache NPM packages in Travis, but this page doesn't come up. Basically including it here for better SEO :wink: since I figure it's a fairly common thing to want to cache.

include node_modules in the caching page

---

user/languages/r.md

See e.g. https://travis-ci.org/rstats-db/RMySQL/builds/119360508#L426
Not sure if I got the links right. Perhaps this information should be placed more prominently.
CC @jimhester @hadley @craigcitro

APT add-on installs also in container-based builds

---

user/notifications.md

This information was incorrectly copied from the `webhooks` section.
Our Slack notification addon is not intended to support `on_start` notifications.

remove on_start from slack notifications

---

user/encryption-keys.md

There is an issue on this page because all of the code snippets but this one involve "rooms" the child of "campfire". This pull requests fixes that discrepancy and makes all code snippets have "rooms" as a child of "campfire".

Make format between code snippets consistent

---

user/installing-dependencies.md

This fixes the example to make it clear that Travis would need to have the `-y` argument passed when running `apt-get install`, or it'll hang for a response.

Add -y to 'sudo apt-get install varnish' command

---

_includes/sidebar.html
user/sonarqube.md

@BanzaiMan Here's a first version of the documentation page for the SonarQube add-on. Feel free to give feedback on it.
@dbmeneses and @henryju: as this is markdown, you can just go on the sonarqube.md file and click on "View" to have something readable and give feedback. Thanks.

First version of the SQ add-on doc

---

user/languages/community-supported-languages.md
user/languages/nix.md

This adds a basic Nix page detailing how to setup and use the Nix
language with Travis projects. This is a companion PR to travis-ci/travis-build#745.

Add Nix page to programming language documentation

---

user/pull-requests.md

When reading about [Building Pull Requests](https://docs.travis-ci.com/user/pull-requests), i was looking for some sort of differentiation between **Build pushes** and **Build pull request**. Hopefully this clarification is good!

updated differentiation between pushes and PRs

---

user/uploading-artifacts.md

Right now the example which explains how to upload specific files uses colon (":") as a delimiter meaning it won't work with files which contain colon in the name.
This minor PR adds a note which clarifies this.
On a related note - I didn't test it out, but it seems like Travis assumes colon as a delimiter. Is this true? Or can you use arbitrary character (\0 or \n seems like a better default delimiter)? If you can't, can you escape paths which contain with a delimited (e.g. with double quotes)?

[user/artifacts] Add a note about file names and delimiter

---

user/languages/android.md

Android SDK version along with buildtools version have been updated in all examples, since they represent the latest available official versions from Google (https://developer.android.com/tools/sdk/tools-notes.html) 
Notice: this can be merged as soon as https://github.com/travis-ci/travis-cookbooks/pull/490 is merged.

Update Androd SDK version to 22, buildtools to 22.0.1

---

user/customizing-the-build.md

This pull request clarifies the documentation, showing how the `after_*` stages can cause a build failure.

More accurate documentation about `after_*` stage and build failure

---

user/customizing-the-build.md

I attended a workshop at Wicked Good Ember where we added Heroku deployments via Travis, which produced a [diff that was mostly full of trivial indentation and quotation changes](https://github.com/backspace/wge-advanced-2016/commit/7f2bd8c6c23255d680c156606a1a3394a82ba120#diff-354f30a63fb0907d4ad57269548329e3).
I submitted a [pull request](https://github.com/ember-cli/ember-cli/pull/6082) to Ember CLI to have the blueprint `.travis.yml` files match the indentation of the output of the Travis gem, but it was rejected because the documentation shows indentation that doesn’t match the gem output.
I suggest that we either update the documentation to show `.travis.yml` examples that match the output of the gem or change the gem to match the indentation of the documentation. If the latter …

Update indentation to match travis gem output

---

user/languages/dart.md

To address documentation test failures [like this one](https://travis-ci.org/travis-ci/docs-travis-ci-com/builds/145087411#L207).

Fix link to Dart install page

---

user/deployment/surge.md

Correction to the documentation of the use of deployment with surge.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/travis-ci/docs-travis-ci-com/668)

Always ask to skip cleanup on generated files

---

_data/xcodes.yml

- bump to Xcode8b6
- `brew update` and `brew upgrade` ran
- `gem update` ran for all rubies
- installed latest node 4, 5, and 6 with `nvm`
- latest `cocoapods` beta install and `pod setup` ran for all pre-installed rubies

Xcode8b6 update

---

user/pull-requests.md

Due to the documentation of environment variables `TRAVIS_PULL_REQUEST` returns either a number of the pull request or `false` if it's not a pull request. Therefore the check `= "true"` won't work as expected.

Fixed incorrect use of TRAVIS_PULL_REQUEST.

---

user/multi-os.md

The `before_install` step was missing an underscore.

Added missing _ to before_install

---

user/triggering-builds.md

Since %2F is the escaped form of a slash, people are assuming
it can just be converted to a slash. That results in failures,
though, because the slug needs to be treated as a single URL
segment.

Add note about %2F requirement in request URL

---

_data/xcodes.yml

Includes:
- Xcode8 GM `8A218a`
- `brew update && brew upgrade` was run
- Updated CocoaPods to [`1.1.0.beta.2`](https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.beta.2)
- Ran `pod setup` in all the pre-installed Rubies.

Updating Xcode8 to GM Seed 8A218a

---

user/notifications.md

Adds a link that shows a sample Python implementation inside a Django view, similar to the Sinatra app.  Feel free to take the code and stick it in a repo like the Sinatra app as well.

Add link to Django Webhook Signature Verifier

---

user/caching.md

This corrects the behaviour of pull request caching and splits the information in two separate lines.

clarify pull request caching behaviour

---

user/notifications.md

One of our Enterprise customers recently gave the feedback that the documentation for encrypting Slack notifications when a channel was specified was not immediately apparent, and took a bit to figure out.  This is an attempt at making that a little clearer with an example.

Clarify syntax around encrypting Slack notifications with channel specified

---

user/osx-ci-environment.md

We added
- pyenv (via homebrew)
- virtualenv (via pip)
- numpy (via pip)
- scipy (via pip)
- tox (via pip)

Detailing some python tools we've added to the default 7.3 image

---

user/database-setup.md

I added Docker to my builds which switched me to the Trusty image. It took me a while to figure out why MySQL stopped working with the default MySQL instructions. This note tells users that they must install MySQL themselves on Trusty.

Add note that users must use the MySQL 5.6 instructions for Trusty

---

user/ci-environment.md

The naming of "standard" is very misleading, especially because it is not the _default_ environment.

Rename "standard" environment to "sudo-enabled"

---

user/notifications.md

This corresponds to https://github.com/travis-ci/travis-tasks/pull/72

Remove Authorization header info from webhook

---

user/languages/python.md

[Nosetests has been in maintenance mode for quite a while now](http://nose.readthedocs.io/en/latest/) with the [last contribution many many months ago](https://github.com/nose-devs/nose).
Therefore I don't think Travis docs should default to nose (which is likely to be picked up by new users) but instead promote pytest, an alternative with a very active community and active development.

Python: do not default to dead nosetests, suggest pytest instead

---

user/languages/java.md

As requested [here](https://github.com/travis-ci/travis-ci/issues/5081#issuecomment-257889136) I'm just adding this to the public docs for other users

Include JDK 8 Build workaround in public docs

---

user/firefox.md

This updates the firefox addons doc to match my patch adding firefox developer and nightly versions.

Updated docs to match current firefox addons

---

user/ip-addresses.md

<del>A potential problem with this update is that, with the rollout of replacement container-based ubuntu precise capacity, it may not make sense to call out a precise/trusty split.</del>
(already collapsed 'em)

Update NAT IP addresses

---

user/customizing-the-build.md

[Here](https://docs.travis-ci.com/user/customizing-the-build#Explicity-Including-Jobs):
"Explicity Including Jobs" should be "Explicitly Including Jobs".

Fixed typo in header

---

user/ip-addresses.md

This updates the IPs to match the hostname they're assigned to
```
$ host workers-nat-org-shared-2.aws-us-east-1.travisci.net
workers-nat-org-shared-2.aws-us-east-1.travisci.net has address 54.87.141.246
workers-nat-org-shared-2.aws-us-east-1.travisci.net has address 52.45.185.117
workers-nat-org-shared-2.aws-us-east-1.travisci.net has address 52.54.31.11
workers-nat-org-shared-2.aws-us-east-1.travisci.net has address 54.87.185.35
$ host workers-nat-com-shared-2.aws-us-east-1.travisci.net
workers-nat-com-shared-2.aws-us-east-1.travisci.net has address 54.89.89.104
workers-nat-com-shared-2.aws-us-east-1.travisci.net has address 52.54.40.118
workers-nat-com-shared-2.aws-us-east-1.travisci.net has address 52.45.220.64
workers-nat-com-shared-2.aws-us-east-1.travisci.net has address …
```

Swap some of the .org and .com NAT IPs

---

user/code-climate.md

We've released a new version of our Ruby test reporter, that works differently than it used to. Additionally, we are converging on keeping all of our test coverage documentation up to date at our documentation site, so this moves other languages there as well.
This replaces #787

Update Code Climate Docs

---

user/languages/perl6.md

Got caught out when I put in `- 2016.10` and the trailing 0 went missing!

Quotes around version numbers

---

user/languages/python.md

This was brought up by a user in a support conversation.

Mention version discrepancy for pytest/py.test in documented example

---

user/ci-environment.md

This configuration is specified and prioritized in our Scheduler app at:
https://github.com/travis-ci/travis-scheduler/blob/master/lib/travis/queue/docker.rb#L11-L13

Set again the default routing for Linux jobs.

---

user/deployment/codedeploy.md

I simply removed the code block that wasn't linked to. I'm assuming this
was just the product of a bad merge.
This was reported by a user via a support ticket.

Remove duplicate documentation block

---

user/customizing-the-build.md

Changed "Bitbucketc" to "Bitbucket"

Typo in spelling of "Bitbucket"

---

user/database-setup.md

Following https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/
the version information has been updated. Please push not before the
change.

Update linux postgres versions

---

user/languages/android.md

x86 emulators aren't supported yet on Travis CI. See travis-ci/travis-ci#1419.
Based on feedback from [HS 44939](https://secure.helpscout.net/conversation/282411357/44939/?folderId=30784).

Removed x86 emulator from samples

---

user/database-setup.md

since it varies across distros and job execution envs

Remove explicit postgis version

---

user/deployment/codedeploy.md

Explicitly mention that Travis will attempt to deploy to us-east-1 unless otherwise specified in the travis.yml file

Update CodeDeploy instructions

---

user/build-environment-updates/2016-12-08.md

-  kernel upgrade from `4.8.7` to `4.8.12` for [CVE-2016-8655](https://security-tracker.debian.org/tracker/CVE-2016-8655)

Update for CVE-2016-8655

---

user/docker.md

If you add the -e flag you get the following warning:
> Flag --email has been deprecated, will be removed in 1.13.

Removed -e flag from docker login command

---

user/deployment/cloudfoundry.md

I work on a Cloud Foundry deployment (cloud.gov), and a couple of our users ran into potential security problems because they didn't receive clear documentation about the need to escape special symbols in passwords run through `travis encrypt`. This change adds a reminder about that to the Cloud Foundry page, with a link to the main info about escaping symbols (https://docs.travis-ci.com/user/encryption-keys#Note-on-escaping-certain-symbols).
(For additional context, see https://github.com/18F/cg-site/pull/637 for the update I made to our local Cloud Foundry docs, and https://github.com/18F/cg-product/issues/517 for the user reports.)
This edit also includes minor copyedits since I was already editing the page.

Note on CloudFoundry page that symbols in passwords must be escaped

---

user/notifications.md

Default templates are different for Push and PR builds, and also direct
users to Slack documentation for further information.

update Slack notification docs

---

user/apps.md

Follow-up of https://github.com/travis-ci/docs-travis-ci-com/pull/892
After continued server errors, Ducksboard has been removed from the Apps
and Integrations page.  If all would get up again, we would welcome a
notification or PR.

Ducksboard references removed

---

user/languages/groovy.md
user/languages/java.md

Synchronize the documentation with what is currently executed by default.
The code can be found here:
https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/shared/jvm.rb

Fix Maven CLI arguments

---

user/encryption-keys.md

This is a simple PR:
* Encapsule encrypt string value in quotes in order to allow special chars
Alternatively, I could add another example block slightly below this one including some special chars & the quotes. 
I figured the more concise would be better, but I'll leave that decision to you maintainers & will make the change if requested 😄

[FIX] Quote encapsulate encryption value

---

user/customizing-the-build.md

The worker boxes are provided by us, not the community.

Rephrase build matrix plea

---

user/languages/android.md

The 2.3 android gradle plugin comes with a [new build cache](http://tools.android.com/tech-docs/build-cache).

Add android build cache

---

user/languages/javascript-with-nodejs.md

The example case is: if we're building a NodeJS app for AWS Lambda (which only supports up to v4.3).
On development machines we're using node v6 and yarn, but to deploy the app into Lambda we need to use node v4.3 in the `.travis.yml` file and force the usage of `npm install` since some of the dependencies will fail if installed using yarn.
This is one of those libraries:
```
error sol-redis-pool@0.3.2: The engine "node" is incompatible with this module. Expected version ">= 4.5.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Add guides on how to disable yarn

---

user/caching.md

Fix for #416
I think this covers it. @MariadeAnton want to confirm?

More cache clarification

---

user/environment-variables.md

At the beginning of the [environment variables documentation](https://docs.travis-ci.com/user/environment-variables) there is a link to the element `#Defining-Variables-in-Repository-Settings`, which does not exist (link target: https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings).
When JavaScript is enabled, the link works anyway, but with this change the link works also if JavaScript is disabled/blocked (just like the other links on that page).

Fix broken link in environment variables documentation

---

user/languages/python.md

as per https://github.com/travis-ci/travis-ci/issues/7085 add python 3.6 to listed supported versions.

add python 3.6 to listed versions

---

user/common-build-problems.md

i.e. `osx_image: xcode8.1 or xcode8.2`
See https://github.com/travis-ci/travis-ci/issues/6791

Added workaround for code signing to work on our macOS Sierra VMs

---

user/build-configuration.md

The use case is Pages-only repositories, where the maintainers run the build with Travis, and want all branches and pull requests to be run.

add hack for building all branches

---

user/triggering-builds.md

The "Triggering builds from the API" docs might be confusing for Travis PRO users, as the sample requests are made to the `.org` endpoint. I added a note for this, similar as it is done before for the CLI commands for Travis PRO.
The change looks like this:

Add note to use .com endpoint for Travis PRO - Triggering builds docs

---

user/apps.md

We wrote an Elixir client (https://github.com/localytics/travis.ex and blog post http://eng.localytics.com/best-practices-and-common-mistakes-with-travis-ci/), and would love to get it into the docs!

Add elixir client

---

user/deployment/script.md

An example with simple arguments as well as an example using one of Travis' built in environment variables.
See https://twitter.com/chrisguitarguy/status/824980175813218304
We pay for travis-ci.com and were trying to use the same deploy script to push to multiple environments. You can pass arguments to a script deployment which was not at all clear in the docs and took me trying it out to make sure.
Anyway, I think it's worth it to include some examples. Show how flexible a script deployment really is.

Add Argument Examples to Script Deployments

---

user/deployment/pypi.md

Warn that the minimal example is unsafe and explain how to use an
encrypted password instead, linking to the TravisCI documentation.

Clarify how to encrypt a PyPI deplopyment password

---

user/migrating-from-legacy.md

I believe this information is now outdated as the specs of our sudo-enabled VMs are probably faster than what we had on the Legacy infrastructure.

Remove faster builds note

---

user/speeding-up-the-build.md

- Fix unlinked link(!)
- Change wording so link text looks nicer.
- Use -j rather than --jobs in the example to try and be bsdmake
friendly (although travis appears to use GNU make by default in its
OS and Linux environments).

Update parallel make notes

---

user/deployment/lambda.md

Update AWS Lambda documentation to be more likely to be correct for most users after I found the "minimal configuration to be insufficient when followed.
1. The ```region``` value should be present (even though it is optional) as the majority of users worldwide probably _aren't_ using ```us-east-1```.
1. Using a value of ```index.handler``` causes ```index.index.handler``` to be used instead, causing the lambda to fail. ```handler``` is sufficient.
1. Add the ```runtime``` value and set to  ```nodejs4.3``` as ```nodejs``` is now deprecated and causes [deployment to fail](https://travis-ci.org/martincostello/alexa-london-travel/builds/196336961#L333).

Update AWS Lambda documentation

---

user/caching.md

Searching for the string `*--` in the repo did not reveal other
occurances.

Fixed wrong -- translation into –

---

user/caching.md

Removing the reference to https://github.com/travis-ci/travis-build/pull/148 where not a lot of movement has been seen.

Remove unnecessary reference to possible future change

---

user/languages/ruby.md

Document workaround for slow JRuby installation on GCE

---

user/notifications.md

It seems that for Hipchat's API v2, the room name *is* case-sensitive. We recently got one report about Hipchat notifications that stopped working with the v1 API, and after some investigation we think it's very likely that case sensitiveness might be being enforced in v1 too.
Just a small note in case someone experiences any problem again :)
Please, @plaindocs, could you please take a look? Thank you!
cc @MariadeAnton

Add small comment about Hipchat room names being case-sensitive

---

user/languages/python.md

This reverts the tip given at https://github.com/travis-ci/docs-travis-ci-com/issues/361

do not recommend --user pip install in container-based

---

user/languages/php.md

apc is not installable on PHP 7+.
See https://github.com/travis-ci/travis-ci/issues/7390

Fix apcu extension name

---

user/customizing-the-build.md

Add a note in the `Safelisting or blocklisting branches` section that notifies the user that safelisting branches causes tagged commits to be skipped. Also, propose an example regex that allows specific tags to be safelisted.

feat(doc): Add note about safelisting branches and tags

---

user/customizing-the-build.md

After some confusion with the `fast_finish` feature, it seems that some people (me included) were understanding that activating `fast_finish` in a build would stop a build as soon as one job fails.
However, after some tests and [from @BanzaiMan's comments:](https://github.com/travis-ci/travis-ci/issues/7231#issuecomment-275745395)
> fast_finish sets the build results when all the required jobs finish, without waiting for all the jobs (which may be allowed to fail) to finish.
`fast_finish` does only have an effect for builds in which there are `allowed_failures`, but not for a regular build in which all jobs are required.
Another confusion here is that `fast_finish` does not cancel the remaining jobs, it sets the result of the build, but the remaining jobs (allowed failures) will still …

Fast finish only determines the status of a build if required jobs finished

---

api/index.html

This updated the update GitHub Web Interface link from the Applications directory to the page to create a new personal access token in GitHub.

[api docs] update GitHub Web Interface link to create a new personal access token

---

user/languages/javascript-with-nodejs.md

Include information about newer versions, there were many references to 0.12 and no references to version 7

Update javascript-with-nodejs.md to include ver 7

---

user/languages/php.md

- add newer HHVM LST versions to the list
- hhvm 3.6 is available on precise

add newer HHVM LST versions to the list

---

user/docker.md

Closes https://github.com/travis-ci/docs-travis-ci-com/issues/953
Closes https://github.com/travis-ci/docs-travis-ci-com/issues/1017
This PR adds a section with the required steps to update to the last Docker version. The Docker version preinstalled in Trusty sudo-required is:
```
$ docker --version
Docker version 1.12.3, build 6b644ec
```
Also, I'm including a note about builds with `services: docker` configured being routed by Trusty. I've seen a couple questions about this lately, as users seem confused because they're setting `dist: precise` but this is ignored. For the record, this is done here: https://github.com/travis-ci/travis-api/blob/d9b80d82f1b88d3b8fd1f05da4b5e74bfda68b9e/lib/travis/model/build/config/dist.rb#L10-L11
This looks like:
and
Any feedback would be appreciated, …

Docker: document steps to update to last version and route to Trusty

---

assets/stylesheets/_base.sass

display direct `p` children of `li` as inline, fix line break in lists

---

user/private-dependencies.md

I've seen a couple of reports today in which there was some confusion setting SSH keys to access private dependencies but the dependency URL wasn't updated appropriately to have the format to clone the submodules via SSH.
I thought that converting this paragraph to a note would highlight it. What do you think?
This change looks like:

Add Note styles to protocol details on private dependencies

---

user/deployment.md

I've seen that we're commonly using the term "slug" around the documentation, so I thought it would be interesting to use it here too as the "name along with the owner" mention seems to be confusing.
What do you think @plaindocs?

Clarify repo option for deployments

---

user/triggering-builds.md

This documents the `merge_mode` that can now be passed to API when triggering build requests.

Document merge_mode for triggering builds via API

---

user/deployment/pages.md

It's not so much that there's no default, but rather that the default is to _change_ the current GitHub custom domain setting to remove custom domain support.
It might be a bit friendly if an empty `fqdn` setting didn't change the GitHub configuration.

Better  `fqdn` default description for pages deployment

---

user/docker.md

Lately we included [this note about builds being routed to Trusty when services: docker was configured](https://github.com/travis-ci/docs-travis-ci-com/commit/bda572ba29615d3a188c49439a75ee3b533516e4), but I think this could be improved by detailing that the builds are actually routed to the Trusty `sudo: required` infrastructure.

Clarify route to sudo-required infrastructure for services: docker

---

user/caching.md

The "Build pushes" option was recently renamed to "Build branch updates" in https://github.com/travis-ci/travis-web/commit/07cb38f1ac0495b41c380e1fd58b41347677a290.

Update "build pushes" wording to "build branch updates" in caching

---

user/build-stages/deploy-npm.md

The `gem` property looks like a copy-paste issue since it's not documented anywhere on https://docs.travis-ci.com/user/deployment/npm

build-stages/deploy-npm: Remove "gem" property

---

user/languages/perl6.md

This PR gives the Perl 6 docs a much needed update.  The biggest change here is to replace the discontinued module installer (`panda`) with the current module installer (`zef`).

Update Perl 6 docs

---

user/languages/julia.md

The way Julia's package manager works, the minimum supported Julia version for a package is set in a `REQUIRE` file. The Julia versions tested on Travis should generally start with the minimum supported Julia version (consistent with `REQUIRE`), plus anything newer that the package maintainer wants to also support and test against. The use of `release` is a bit harmful in that respect, since packages that haven't seen any activity in a while will gradually stop testing against the release Julia versions that they claim to support according to their `REQUIRE` file. We've modified the package template's `.travis.yml` to instead favor using specific version numbers. I'll be submitting a set of pull requests to existing packages to encourage them to do the same. Once it's no longer in use, I …

Remove mention of `release` option under julia: key

---

user/languages/perl6.md

This way only module dependencies get installed and the `prove`
command tests the content of the repo, without having the very
same module already installed on the system.

Add --depsonly to pre-testing installation

---

user/build-environment-updates/2017-05-05.md

Fixes the typo on:
https://docs.travis-ci.com/user/build-environment-updates/2017-05-04/

Correct date in 2017-05-04 build environment update

---

user/notifications.md

According to [Travis-Hub](https://github.com/travis-ci/travis-hub/blob/ac97c871a12330c05f64bc8a478e22c6dbf3562b/lib/travis/addons/serializer/webhook/build/message.rb#L22-L29), it seems we're missing the "Canceled" and "Errored" states in the webhook notification docs :)
The full list would be:
```ruby
pending:  'Pending',
passed:   'Passed',
failed:   'Failed',
broken:   'Broken',
fixed:    'Fixed',
failing:  'Still Failing',
errored:  'Errored',
canceled: 'Canceled'
```

Add canceled and errored states in webhook notifications

---

user/apps.md

I added info about knapsack gems which have integration with Travis-CI.
Knapsack splits tests across CI nodes and makes sure that tests will run comparable time on each node.
https://github.com/ArturT/knapsack
https://github.com/KnapsackPro/knapsack_pro-ruby

Add info about knapsack gem in 3rd party libraries

---

user/languages/rust.md

Rust projects can define a workspace which is a set of crates that will all share the same Cargo.lock and output directory. Without modifying the build script to pass `--all` to the various build commands, only the root crate will be built and tested. Or, if the workspace has no root crate, the build and test commands will fail with the following error:
error: manifest path `/path/to/crate/root` is a virtual manifest, but this command requires running against an actual package in this workspace

Rust: add example for workspace projects

---

user/languages/javascript-with-nodejs.md

Took me a few minutes to find out how to do it as I could not see it on the JavaScript page.  Hopefully if more people use it'll also decrease build times significant on servers, halved the runtime of mine!

Add npm caching to javascript-with-nodejs.md

---

user/common-build-problems.md

Please consider merging when the customer replies that it fixes it.

Document usage of Fastlane's `import_certificate` statement on macOS Sierra

---

user/common-build-problems.md

Reverts travis-ci/docs-travis-ci-com#1094

Revert "Document usage of Fastlane's `import_certificate` statement on macOS Sierra"

---

user/migrating-from-legacy.md

The whitelist is not being extended, so suggest the recommended workaround of `sudo: required`.

Change instructions about whitelisting packages

---

user/deployment/pages.md

Adds warning that provider is experimental.
Since https://github.com/travis-ci/dpl/commit/c6696b38d2c5e5941d2aa51edbac94b066a9c4d2  deployments will show:
> !!! GitHub Pages support is experimental !!!
We should either remove the experimental warning, or add something to the documentation -the warning took me by surprise. Not sure what the warning should say, maybe this will do, I'll leave that up to your judgement :smile:
/cc @BanzaiMan

Adds warning that provider is experimental.

---

.travis.yml
Gemfile
Gemfile.lock
_plugins/post_handler.rb
_plugins/select_env_var_generator.rb
_plugins/webhoook_payload_doc_handler.rb
config.ru
user/notifications.md

This PR adds a POST endpoint, which is only valid at `/update_doc_webhook_payload`.
The idea here is that the docs app will receive the live (and hence always up-to-date) webhook payload, and update the gist (to be determined later) with that payload when we receive a POST request on the new endpoint.
This resolves https://github.com/travis-ci/docs-travis-ci-com/issues/1199.

Keep webhook payload up to date automatically

---

user/languages/r.md

My last PR mistakenly pointed to the tests, not the source itself. Classic.
PTAL @jimhester @BanzaiMan

Update the link to the R builder source.

---

user/languages/csharp.md

- Updated dotnet version to current
- Added a bit about the requirement of having a "script" command, and added one in the example.
This change is related to [this issue](https://github.com/travis-ci/travis-ci/issues/7760#issuecomment-305433367)

Update .NET Core sample yml file

---

_layouts/en.html

We changed the default branch name from `gh-pages` to `master`.

Fix GitHub edit link

---

README.md

There seems to be the word `master` at the very beggining of your readme for no obvious reason. It is also stoping the `h1` on that line being parsed correctly.
This PR simpily removes the word, which should fix the broken rendering too.

Removed 'master' from the first line.

---

user/deployment/heroku.md

Anvil is completely broken, so it will be removed from dpl soon.
git-ssh and git-deploy-key will stop functioning when legacy API is dropped on June 26, 2017.

Remove mention of anvil, emphasize deprecation warning

---

user/docker.md

Reference: https://docs.docker.com/engine/installation/linux/ubuntu/#uninstall-old-versions
Some of the conversation re: name change: https://github.com/moby/moby/issues/31514

RENAME: docker-engine -> docker-ce. package docker-engine is deprecated

---

user/deployment/heroku.md

These have been deprecated on 2017-06-26.

Remove deprecated Heroku deployment strategies

---

user/for-beginners.md

Build status is correctly pointing to https://travis-ci.org/repositories, which returns a 404.

Fix URL 404 error in Beginner's guide

---

user/caching.md

In order to make ccache available as the default compiler for the following commands, the modified PATH must be exported to the environment.

Fix "ccache on OS X example"

---

user/deployment/firebase.md

Adds docs for support for adding optional messages when deploying with the Firebase provider.
See travis-ci/dpl#651 for main PR.
Fixes travis-ci/travis-ci#7872

Add docs for support for message in Firebase provider

---

Rakefile

This would indirectly invoke gen_trusty_image_data,
to ensure that we fetch the docker image data on deployment.
This resolves #1317.

Make assets:precompile depend on build

---

.travis.yml

This is getting silly. 
Turning CI off so we can get the build to pass.
Somehow related to https://github.com/gjtorikian/html-proofer/issues/170 ?

Turn it off and turn it on again

---

user/database-setup.md

It is yielding 403 now.
Given the state of Basho, it is highly unlikely to come back.
We'll simply remove the link.

Remove link to docs.basho.com

---

user/build-environment-updates/2017-08-17.md

These images have been deprecated since December/January, this lets people know that they are actually being run on 7.3, not 6.4 (unless they specify 6.4).

Add build env update about old beta xcode 6.x deprecation

---

user/docker.md

Using "docker-engine" caused a missing package error. Changing it to "docker-ce" fixed it.

Fix apt-get command for updating Docker

---

user/common-build-problems.md

section on starting container locally.

Remove "precise" references from common build problems

---

user/build-environment-updates/2017-09-06.md

to note that they are specific to container-based, given that we now
unsed these vars on sudo-enabled.

Update notes around _JAVA_OPTIONS and MALLOC_ARENA_MAX changes

---

user/running-build-in-debug-mode.md

This guide [here](https://docs.travis-ci.com/user/running-build-in-debug-mode/) contains a small grammatical error- it says "The push access permission is required", when just "Push access is required" is correct.

Fixed small grammatical error in the running builds in debug mode guide.

---

user/deployment/lambda.md

When following the travis-ci documentation, you should be able to sucessfully deploy your application to AWS Lambda without any errors
The user recieves an error stating that they do not have permission to execute 'lambda:GetFunction'.
This pull request adresses the following issues:
* When deploying to AWS Lambda - lambda:UploadFunction is no longer used by AWS
* lambda:GetFunction permissions are now explicitely required.
When following the travis-ci documentation you should have confidence that the proposed solution will work. Adding lambda:GetFunction allows this to be the case.
Also, travis-ci documentation should not include any depreciated permissions as a matter of course. Removing lambda:UploadFunction mades this the case.

[FIX] AWS Lambda Deploy Policy

---

user/notifications.md

The [Configuring Build Notifications](https://docs.travis-ci.com/user/notifications) page does not contain any Node.js examples in the [Verifying Webhook Requests](https://docs.travis-ci.com/user/notifications#Verifying-Webhook-requests) section. I've created some examples and added a link to their Github repo.

add webhook verification example for nodejs

---

user/languages/go.md

-t was introduced in Go 1.2.  The behavior of Travis (rightfully) is flipped from what the docs say.

Fix flipped go get flags in Dependency Management section

---

_includes/sidebar.html
user/reference/overview.md

- Updates virtualization environments overview
the long-term Ubuntu Precise 12.04 environment is available in fully virtualized infrastructure, per https://blog.travis-ci.com/2017-08-31-trusty-as-default-status
- Removes 2015 migration guide from legacy to container-based infra and redirects to overview page
- Adds a reference to deprecated virtualization environments, linking to the corresponding announcement blog posts

Update build virtualization environments

---

user/database-setup.md

MongoDB's 'addUser' was deprecated since v2.6 and no longer works on v3.4 and up.

MongoDB 'addUser' no longer works

---

_includes/sidebar.html

Having documentations pages highlighting the sidebar helps find related content, or establish that there is none.

Add link to 'conditional-...' in sidebar

---

user/languages/rust.md

You can see the broken code block here: https://docs.travis-ci.com/user/languages/rust/#Dependency-Management

fix syntax highlighting for a code block in the rust doc

---

_includes/c11-cpp11-and-beyond-and-toolchains.md

there was an indentation issue in the gcc on Linux section. One line was not indented at all, which when used as it is, travis would fail to parse the yml.

Fixed indentation issue in gcc on Linux section of c11-cpp11-and-beyond-and-toolchains.md

---

user/database-setup.md

Hello,
Just above in the file there is the `env` setup `DB=postgres` at https://docs.travis-ci.com/user/database-setup/#Using-environment-variables-and-a-before_script-step
Better to be consistent in this example.
Cheers

Consistent example in DB setup documentation

---

user/deployment/releases.md

Fix a typo in a config key for GitHub Releases

---

user/enterprise/platform-tips.md

This PR adds instructions on how to obtain and configure a Let's Encrypt certificate for a Travis CI Enterprise installation in the platform tips section.

Add let's encrypt instructions to Enterprise platform tips

---

user/languages/nix.md

NixOS/nixpkgs have removed .travis.yml and the broken link is currently causing the build to fail: https://travis-ci.org/travis-ci/docs-travis-ci-com/builds/301462591

Remove nixpkgs broken link

---

user/database-setup.md

Since the locales listed in our docs are outdated (we install a lot more, and they also depend on the image), we've discussed this as part of the [Trusty Q4 work](https://github.com/orgs/travis-pro/projects/13) decided it's better to remove them altogether.

Remove locale list from Postgres docs

---

user/sauce-connect.md

Builds are currently failing due to broken saucelabs links: https://travis-ci.org/travis-ci/docs-travis-ci-com/builds/303492412?utm_source=github_status&utm_medium=notification
I tried to update them to match the current sign-up process.

Update saucelabs links

---

user/languages/php.md

References: 
- https://github.com/travis-ci/travis-cookbooks/issues/908
- https://github.com/travis-ci/travis-ci/issues/8516#issuecomment-332979598
Since we didn't think it's worth downgrading PHPUnit, documenting the workaround seems like a good middle ground.

Document workaround for PHPUnit on HHVM

---

user/deployment/releases.md

I'm in the process of getting to know how to properly set up Travis CI configs. GitHub Pages Deployment uses the `local_dir` option, but GitHub Releases Deployment uses `file` in addition with `file_glob` to specify the files and or folders. There is no mentioning of `local_dir` in `lib/dpl/provider/releases.rb` at all.
This had me confused and I think the section about the `local_dir` option should be removed from the docs about GitHub Releases Deployment.

Remove option `local_dir` from docs about GitHub Releases Deployment

---

user/ip-addresses.md

This PR is based on https://github.com/travis-ci/docs-travis-ci-com/pull/1571, but removes the old IPs as well, and also includes the modifications for `.org`, not just `.com`
It seems that the changes in https://github.com/travis-infrastructure/terraform-config/pull/303 caused our IPs to change, so our docs need to be updated as well.

Update NAT IPs for AWS

---

user/languages/perl6.md

This should fix [GitHub issue 8825](https://github.com/travis-ci/travis-ci/issues/8825).

Update Rakudo default branch name after branch rename

---

user/build-environment-updates/2017-12-11.md

Reference: https://github.com/travis-pro/team-jade/issues/762
Add a page for the 2017-12-11 update. 
This initial list of changes is based on the git logs. We still need to cross-check it with the image metadata diffs.

Prepare changelist for the Trusty Q4 updates

---

user/build-environment-updates/2017-12-12.md

We didn't release yesterday, as planned, so the docs should be consistent with the rest of our announcements around the updates.

Fix Trusty Q4 roll-out date

---

user/customizing-the-build.md

I was trying to figure out how to upload test logs and screenshots from successful and failed builds. It's unclear whether the deploy-related steps run on build failures.  From @BanzaiMan's [answer on StackOverflow](https://stackoverflow.com/a/39056573), they are not.

Clarify that deploy steps are skipped on build failure

---

user/environment-variables.md

I feel like this is a common-enough scenario to deserve a note in the docs (and in the Settings page section).

Be more explicit about escaping strings with spaces in Environment Variables

---

user/firefox.md

The final rendering at https://docs.travis-ci.com/user/firefox makes it hard to know that the versions are clickable links.

be explicit about links

---

user/ssh-known-hosts.md

As seen in the addon functionality here: https://github.com/travis-ci/travis-build/blob/a3395b694b00225118582b47432aed9c64614b3d/lib/travis/build/addons/ssh_known_hosts.rb#L48-L51, one can specify the port as well. This just updates the documentation to reflect the existing functionality.

ports can be used with known_hosts, update docs

---

user/languages/php.md

The URL to download `phpunit` is returning a 302 status code and the `curl` command was failing to download the file. Added the `-L` flag to tell `curl` to follow to the new location.

Add `-L` flag to `curl` command

---

user/customizing-the-build.md

.dev is owned by Google and has been added to HSTS preload. It should not be used for this purpose.

use .test instead of .dev

---

user/caching.md

The documentation states that "If a branch does not have its own
cache, Travis CI fetches the master branch cache".  However, this is
not quite true: it fetches the cache of the repository's default
branch, whatever it is called.  While the default branch is indeed
called 'master' in most repositories, that's not always the case.

caching: Travis CI fetches the cache of the default branch

---

user/enterprise/installation.md
user/enterprise/operations-manual.md

@schultyy @plaindocs - how's this look for an addition to the ops manual re: the [docker version mismatch error](https://github.com/travis-pro/team-cyan/issues/50) on old worker installs? Assuming all's ok, I'd like to get things merged asap so we can email it with Meltdown vulnerability recommendations

[Enterprise] add enterprise docker version mismatch error to ops manual

---

user/travis-pro.md

Moving forward, I believe we could use a table so that this is clearer, kind of what GitHub is doing at https://help.github.com/articles/repository-permission-levels-for-an-organization/

Update to match permissions behaviour

---

Rakefile

as it is slightly more reliable than dig.jsondns.org

Switch to dnsjson.com for DNS lookups

---

user/docker.md

I was using the Docker build steps and had to go looking for encryption steps. I thought it would be useful to remind users to do so, and how.

Add link to encryption for env vars

---

user/database-setup.md

The database setup documentation provides an example `config/database.yml` file for using MySQL with ActiveRecord, but it's mislabeled as `.travis.yml`. This corrects this label.

Correct filename in database setup documentation

---

user/common-build-problems.md

`Capybara.default_wait_time` is now `Capybara.default_max_wait_time`:
https://github.com/teamcapybara/capybara#using-capybara-with-rspec

Common Build Problems: Uses the new name of Capybara.default_wait_time

---

user/deployment/script.md

I believe that the current examples assume that the script files are executable and running the example as it is in Travis CI will error with a "command not found (exit code 127)" error.
We've also had several questions about this in Support, so I suggest changing the examples to use `bash` to run the scripts.

Script deployment: run custom scripts with bash

---

user/ssh-known-hosts.md

Explain the new means of adding previously-known SSH host keys
An additional minor change is eschewing die.net, which tends to be
outdated.
To correspond to https://github.com/travis-ci/travis-build/pull/1304.
Also, see #1649.

Reorganize ssh-known-hosts page

---

user/enterprise/build-images.md

This PR updates the Docker in Docker section for Trusty build images. Because these days Docker-Engine is no more and has been replaced with Docker-CE, the old approach we've done with Precise doesn't work anymore. There we had Docker actually running in Docker. 
The approach for Trusty build images looks a bit different though. Here we're using the Host's Docker daemon to execute the commands. The disadvantage is: the user has to clean up after they're done building, the advantage though: fast interaction with Docker ✨

[Enterprise] Docker in Docker for Trusty build images

---

user/enterprise/trusty.md

This PR removes explanations and instructions for the DeviceMapper installer, because it requires people to use `c3.2xlarge` instances on Amazon EC2 which are now deprecated.  The non-DeviceMapper installer works out as good for now.
Also the wording has been changed from AWS/Non-AWS Installation to just Installation to avoid confusion.

[Enterprise] Remove devicemapper installer from docs

---

user/enterprise/trusty.md

This PR removes the beta flags from the Trusty installer page

Remove beta flags from Trusty page

---

user/enterprise/operations-manual.md

This error can be caused by two things:
- Configuration mismatch in GitHub OAuth App
- Hostname mismatch between server and license
We've seen this a couple of times in our support requests recently and therefore adding this case to the Ops Manual.

Add strategies for `Ready state command canceled: context deadline exceeded`

---

user/languages/crystal.md

see travis-ci/travis-build#1325
Reason for this: https://github.com/crystal-lang/crystal/pull/5544
/cc @asterite, @jhass, @waj, and @will

Replace `crystal deps` with `shards install`

---

user/languages/javascript-with-nodejs.md

The JavaScript docs currently only mention support up to Node 8, and but Node 9 is the current version. I tried using `"9"` in my `.travis.yml` and `nvm` downloaded `v9.8.0`. This would update the docs to mention that support 😄

Add mention on JavaScript docs for Node 9 support

---

user/deployment/lambda.md

Removed optional parameters from minimal example, adding an explanation of credential fall back.

Update AWS Lambda dpl provider docs to include changes made in travis-ci/dpl#745

---

user/languages/rust.md

This allows tests to be run against nightly rust without slowing down the overall build.

Add fast_finish to recommended Rust configuration

---

Gemfile
Gemfile.lock
Rakefile
_config.yml
config.rb

Apparently 
> Heroku apps expect the app directory structure at the root of the repository. If your app is inside a subdirectory in your repository, it won’t run when pushed to Heroku.
And when we switched to generating the Slate on the fly we started cding into `slate` and running Ruby, which was causing the weird version issues.
:-( :-(

Move Middleman config to root dir because Heroku

---

user/deployment/opsworks.md

Adding documentation on how to use the new option for updating the revision in OpsWorks App Settings after successful deployment.
PR https://github.com/travis-ci/dpl/pull/783

Opsworks: Update application source setting after successful deploy

---

user/customizing-the-build.md

Explain what happens with skip option in case multiple commits are pushed together
Ref: https://github.com/travis-ci/travis-ci/issues/8204

Explain what happens with skip option

---

user/travis-pro.md

I just corrected a typo  in the ["How can I make a public repository private?" section](https://docs.travis-ci.com/user/travis-pro/#How-can-I-make-a-public-repository-private%3F).

Correct typo of Travis .com in "Travis CI for Private Projects" page

---

user/customizing-the-build.md

(and after_deploy)
I was not aware of this from the documentation and found out via https://github.com/travis-ci/travis-ci/issues/2570

Mention before_deploy can run multiple times

---

user/languages/csharp.md

The default build command in Travis CI is MSBuild since it has been open sourced, and this pull request reflects that.

xbuild has been replaced by msbuild in Travis CI

---

user/deployment/atlas.md
user/deployment/testfairy.md
user/notifications.md
user/private-dependencies.md
user/ssh-known-hosts.md

In `user/ssh-known-hosts.md`, the repeated that is grammatically correct but should be rephrased to avoid confusion.

Minor fixes for repeated words and subordinate that

---

user/database-setup.md

by removing the outdated and doomed-to-be-outdated table of which versions are available where, and adding a section about combining `apt` and `postgresql` addons to install and enable arbitrary versions on both container-based and sudo-enabled Linux.

Update PostgreSQL docs to reflect current reality

---

user/sonarcloud.md

This is the update for the improvements of the SonarCloud add-on that were merged with https://github.com/travis-ci/travis-build/pull/1338.
Sum up:
- no need anymore to specify the "branches" parameter - this is managed automatically by the add-on
- no need anymore to set the GitHub token in the YML file - it must be set inside SonarCloud

SonarCloud add-on update for PR analysis

---

user/enterprise/operations-manual.md

This PR adds a new case to our operations manual where travis-worker wouldn't start because a directory is missing. This is also the first specific case we add for Ubuntu 16.04.

add 'travis-worker is not starting' case to ops manual

---

user/for-beginners.md

Noticed that there's no TOC exist in this section during scraping the index, this patch attempts to add one according to other sections' practices.
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>

Add TOC to for-beginners

---

user/languages/smalltalk.md

With the merge of https://github.com/travis-ci/travis-gatekeeper/pull/207 Smalltalk users now have the option of selecting a `smalltalk_vm`

Add example for smalltalk_vm option

---

user/deployment/releases.md

`travis setup releases --pro` should be run when using the GitHub Apps integration
I used to use the old travis-ci.org services system for my builds. Recently I started using the new GitHub Apps integration but just could *not* get authentication to work.
It wasn't until I dug up the Travis CI blog post for the new integration that I discovered this would require using the travis-ci.com API endpoint instead. Hopefully this change will help others who also get stuck here.
Feel free to make changes to my branch so that this best fits your docs guidelines 👍

Indicate GitHub Apps integration needs `--pro`

---

user/languages/objective-c.md

The Objective-C/Swift pages have text that references outdated default versions of OS X and Xcode. This change corrects that text to match the OS X Build Environment page as well as the tables on both pages.

Update current OS X and Xcode versions

---

user/deployment/npm.md

I initially got confused that thought these were git tags.  Hopefully this clarification will point future users in the right direction.

Clarify that the `tags` option applies to npm

---

user/installing-dependencies.md

Since we don't run apt-get automatically anymore without using the apt addon, updating the docs to clarify this.

Adding note about running apt-get update

---

user/conditional-builds-stages-jobs.md

Whilst the "Known attributes" list does mention this detail, it was easy to miss when copying the examples - and resulted in me emailing `support@`.

Build stages: Clarify that for PRs 'branch' is base branch

---

user/deployment/elasticbeanstalk.md

According to "[Understanding and Getting Your Security Credentials > Access Keys (Access Key ID and Secret Access Key) ](https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys)"
> Do not provide your access keys to a third party, even to help find your canonical user ID. By doing this, you might give someone full access to your account. 
So I think we should encrypt **AWS Access Key ID** same as AWS Secret Access Key. What do you think?

Use encrypted AWS Access Key ID

---

assets/stylesheets/_base.sass
assets/stylesheets/prism.scss

The current `code` styles make text rather hard to read, especially when used a lot in a single sentence or lists. E.g.:
This PR is meant to dial this down a little. I generally feel a more "flat" style feels a little more clean and modern, too:
It also removes the odd curved underline from the format tag on the right side:
Now:
It also removes the border and white background color from code tags in `blockquote` tags (which have a blue background). This looks especially hardcore when there are lots of code tags inside a blockquote. E.g.:
Actual example from current production:
Now:

Code styles readability

---

user/languages/python.md

You should first `pip install -r requirements.txt` and then `pip install .` and not the other way round. The reason is, that the `requrements.txt` carries the dependencies with pinned versions and the `setup.py` only the dependencies (and conflicting version dependencies if necessary).

Corrected order of install steps in example

---

user/web-ui.md

This setting is the default behaviour and is non-editable

remove docs for "Build only if .travis.yml is present" 

---

user/speeding-up-the-build.md

switching from the original URL which now points to an online adds page to the repo page instead

the URL for the phpdbg debugger 

---

user/customizing-the-build.md
user/private-dependencies.md

Otherwise the first machine.github.com will continue to take effect,
if that is still set up.

Overwrite ~/.netrc if token is needed

---

user/docker.md

This makes it consistent with other documents in "Getting started".
Also changed header level for "Examples" section to also appear in the TOC, to make it consistent with build-stages.md.

Change docker.md header levels to make TOC appear

---

user/languages/python.md

Now that [Python 3.7 has shipped](https://docs.python.org/3/whatsnew/3.7.html), this warning not only covers development branches but also production branches of CPython.

Update OpenSSL warning to reflect Python 3.7

---

user/conditional-builds-stages-jobs.md
user/gui-and-headless-browsers.md
user/speeding-up-the-build.md

A bit unsure about the TOC placement, because some of the documents have a bit of text preceding the TOC (like in "Getting Started"), and some of them don't (like in "Core Concepts for Beginners").

Add missing "toc" blocks for the docs in "Getting Started"

---

user/languages/ruby.md

Opscode was dropped from the company name years ago, and the releases
are significantly higher then "0.y.z" now.
Signed-off-by: JJ Asghar <jj@chef.io>

Updated Company name and CHEF_VERSION(s)

---

user/languages/haskell.md

Since Hackage is the standard package repository for Haskell projects, this seems like a good idea.

Link to Hackage deployment in Haskell guide

---

user/deployment/releases.md

Refer to https://github.com/travis-ci/travis-ci/issues/6172#issuecomment-226825661 .
The current documentation states that all paths in `file` field are relative to `$TRAVIS_BUILD_DIR`, but it's not true. For instance, I've spent two hours to understand why Travis creates new Release and it's empty. The thing was I changed the current directory in at `before_deploy` stage.
Also, Appveyor's artifacts path is **always** relative to the building directory, so many users may expect the same behavior from Travis.

clarify GitHub Releases uploading directory

---

user/languages/python.md

pypy2.7 is broken.
Related to https://github.com/travis-ci/travis-ci/issues/9452
It was introduced to the docs in https://github.com/travis-ci/docs-travis-ci-com/pull/1704

python.md: Replace broken pypy2.7 with pypy

---

_layouts/en.html

Looks like there is a bug in allejo/jekyll-anchor-headings/issues/3 that does not show content before the first heading. Introduced in #1909
This PR restores that pending a fix. 
FAO @cotsog -- thanks!

Restore leading content

---

_data/xcodes.yml
user/build-environment-updates/2018-07-31.md
user/languages/objective-c.md
user/reference/osx.md

9️⃣ 4️⃣ 🍎 👏   DON'T MERGE ME YET - the date for switch is set for Tuesday, July 31st. 
We're moving from xcode8.3 -> to xcode9.4 as our default image.  
Meta-docs and communications checklist [here:](https://github.com/travis-pro/team-jade/issues/833)

Docs Updates for new xcode default

---

user/languages/python.md

`pytest` is the new executable name introduced by Pytest 3.0, it's nothing to do with what version of Python is in use. The old `py.test` continues to work but is deprecated.

Remove misleading pytest comment in Python docs

---

user/languages/rust.md

Hi Travis CI! Thanks for all your work in open source 👏 
It seems to me that if we remove an extra 'always' from Default Build Scripts section of rust.md , it will improve the flow of that section. Of course I am open to making additional changes or just leaving as is, let me know 😄

improve readbility of rust.md

---

user/conditions-testing.md

The `travis-conditions` binary (once released) now supports the two subcommands `parse` and `eval` (previous behaviour only supported `eval`). This PR documents that.
The PR also addresses https://github.com/travis-ci/travis-conditions/issues/5.

Conditions subcommands

---

user/languages/objective-c.md

Documentation to accompany changes from https://github.com/travis-ci/travis-build/pull/1448
Includes new section about device destinations, since xcodebuild will require them for iOS testing.

Update documentation for deprecating xctool

---

user/enterprise/upgrading.md

this came up in support! we don't need 1.0 --> 2.0 upgrade docs live, as there are no 1.0 installations any more

[Enterprise] remove 1.0 --> 2.0 upgrade, as 1.0 is sunsetted

---

user/deployment/elasticbeanstalk.md

Added language that makes it clear that the purpose of the bucket_name field is to specify the s3 bucket where travis will store the source bundle that Beanstalk will use to create the new application version and deploy it.

Clarified purpose of bucket_name field of EBS deploy section

---

_includes/c11-cpp11-and-beyond-and-toolchains.md
user/languages/c.md
user/languages/cpp.md

OS X developers who use `compiler: gcc` are actually getting clang.
In the toolchain include and C reference, warn developers that they need to set a specific gcc version, and link to the details in the toolchain section.

OS X gcc is actually an alias for clang

---

user/apps.md

The Travis-CI Piwik dashboard project is deprecated. The site is no longer
in operation. The source code is still hosted on GitHub.
Signed-off-by: James McClune <jmcclune@mcclunetechnologies.net>

doc: travis-ci piwik project deprecated

---

user/installing-dependencies.md

Expand the macOS section of Installing Dependencies with instructions on using the new Homebrew addon instead of running manual `brew` commands.
Also update the section on supporting macOS and Linux in the same .yml to show how to use both addons in tandem.

Update docs for installing dependencies for Homebrew addon

---

user/apps.md

Coded together this client for PowerShell which PowerShell users might find useful: https://github.com/felixfbecker/PSTravis
I added it to both the CLI section and to libraries, because PowerShell is both a shell and an advanced object-oriented programming language, so I felt like it belonged to both and people might look for one under both categories.

Add PSTravis to tools list

---

_includes/logo.html

It's been bothering me whenever I click on the header when looking at the docs and I get taken to a different website than what I expect.
Let me know if linking to .org is still intentional!

Logo links to travis-ci.com instead of .org

---

user/apps.md

The Emacs editor link had a redundant ``http://`` in the URL.
Signed-off-by: James McClune <jmcclune@mcclunetechnologies.net>

fixed emacs editor link

---

user/apps.md

Hi, I'm actively building Travis CI's Golang client library called [go-travis](https://github.com/shuheiktgw/go-travis) and it would be great if you people would add a link to the library! 
go-travis is the only Golang based library which supports Travis CI API V3. It will soon support all the endpoints of  the API V3.
Thanks! 👍

Add go-travis to 3rd party apps

---

slate/source/index.md

@plaindocs hi! 👋 
It was brought to our attention that there was a typo here, so this corrects it. Let me know if this is not the way to update these old API docs, I honestly can't barely remember how these were built.
Thanks!

Fix anchor link in API 2.1 docs

---

index.html

I found these two links not working properly:

Fix some links on home page

---

user/caching.md

I fiexed link of ` caching shortcut` of caching.md.
https://docs.travis-ci.com/user/caching/#Bundler : Do not work
https://docs.travis-ci.com/user/caching/#bundler : Work

Fixed link of ` caching shortcut` of caching.md

---

user/environment-variables.md

[I was not the only one](https://stackoverflow.com/questions/40294597/how-to-properly-define-multiple-env-variables-on-travis-yml) confused by the paragraph on "multiple environment variables per build" and reading it so that if each entry in the `env` array contains exactly one variable, they will be all applied to a single build.
This PR attempts to describe the actual behavior of the build system unambiguously.

Environment variables: disambiguation

---

user/reference/osx.md

@mjm suggested adding the Homebrew addon to the OS X documentation in https://github.com/travis-ci/docs-travis-ci-com/pull/2017#issuecomment-421444250
This pull request obsoletes #2017 and #2001.

OS X: recommend the Travis Homebrew addon in the Homebrew section

---

user/reference/osx.md

Mac builds _can_ take advantage of `jdk` keys.
The older images come with `jdk_switcher`, which is effective for JDKs up to 8;
the new ones will use `install_jdk.sh`, which can effective for JDKs 10 and later.

Rephrase OS X image and JDK versions

---

user/languages/android.md

According to https://github.com/travis-ci/travis-ci/issues/7331#issuecomment-316790695, `sdkmanager` should already be available. Even if the `android` command is not deprecated in Travis CI’s environment, I’d suggest updating this command since it’s usually ran on the local development machine.
Fixes #1299.

Replace `android list sdk` with `sdkmanager --list`

---

user/deployment/elasticbeanstalk.md

I was unable to use this config since the example missed the secure key for access key id.

secure key is needed when using encrypted key id

---

user/enterprise/upgrading.md
user/enterprise/worker-configuration.md

This explains in detail how to setup worker behind a proxy, with all
required and optional environment variables for that.
Also, it updates our 'Update travis-worker' docs to show users how to update
worker on 16.04+

Explain how setup worker behind a proxy

---

user/caching.md

A lack of a reference creates an illusion that this is the entire info on this matter since this is reference documentation -- a section on subj is expected to contain full, authoritative info on subj.

Add a reference that completes the information

---

user/languages/elm.md

This fixes a typo in the documentation for elm.

Fix typo defualts to defaults

---

user/multi-os.md

The documentation [always uses “on OS X”](https://github.com/travis-ci/docs-travis-ci-com/search?q=%22on+OS+X%22&type=Code). This instance is the only exception.

Change “in OS X” to “on OS X”

---

user/reference/xenial.md

I was reading the docs and noticed this typo. I figured it was a copy+paste mistake.

Typo fix: "ruby" => "Go"

---

user/caching.md

When I was reading these docs, I had to look quite closely to work out why it was recommended to create an environment variable for `CACHE_NAME`. This PR might make it a little bit clearer, though there are probably ways to improve the language further.

Clarify the purpose of setting the CACHE_NAME var

---

legal/survey-terms-conditions.md

This will make the page appear at: https://docs.travis-ci.com/legal/2018-survey-terms-conditions/

adds permalink to T&Cs survey 2018

---

user/languages/cpp.md

Trivial typo in [Building a C++ Project](https://docs.travis-ci.com/user/languages/cpp/).

Fix typo "CCX_FOR_BUILD" -> "CXX_FOR_BUILD"

---

user/encryption-keys.md

The command here doesn't work and issues an error, "unknown command
--com". I believe the com option should come after encrypt.

Fix command to encrypt for com projects

---

user/languages/csharp.md

* Mono: "xbuild tool is deprecated and will be removed in future updates, use msbuild instead"
* The MSTest framework is actually supported when testing against .NET Core
* NUnit.Runners is deprecated (replaced by NUnit.Console)
* Fixed title capitalization

Updated csharp.md

---

user/customizing-the-build.md

I have encountered an issue with ruby's pronto (automated code review), specifically it's rugged git wrapper. It is caused by the default --depth=50 switch on the git clone command, and can be fixed fully by overriding the depth switch, just as mentioned in the docs. However, I have found no actual mention of the caveats of this solution anywhere, and I think that this information would definitely help the next person having a similar problem, given that pronto is pretty much the standard in ruby CI solutions.

mention ruby pronto issues with shallow cloning

---

user/languages/julia.md

In particular, the description of the default test script for Julia v0.7 and later does not specify that `Pkg.test` uses the `coverage` argument. This corrects that omission.
Further, it was not specified where in the YAML document the coverage service provider specifications should go. That has been clarified.
A note has also been added about the meaning of the `coverage` argument to `Pkg.test`.

Expand on and correct Julia test coverage documentation

---

user/languages/csharp.md

This PR fixes the Nunit console path in the [C# NUnit section](https://docs.travis-ci.com/user/languages/csharp/#nunit), see related forum post https://travis-ci.community/t/documentation-is-outdated-on-nunit-section/1705

fix nunit console path

---

user/languages/javascript-with-nodejs.md

As to what directory is added to the cache.
To correspond to https://github.com/travis-ci/travis-build/pull/1642.

Clarify `cache: yarn` behavior

---

user/languages/python.md

Updating documentation on Python versions to specify that the stable release of Python 3.7 is supported on Xenial.

Updating with info about stable python 3.7

---

user/languages/csharp.md

C# was the only programming language doc page without a table of contents:
~/Documents/Github/docs-travis-ci-com/user/languages $ grep -L "^## " *
csharp.md
I also fixed the capitalization of xUnit
Screenshot:

Adding Table of Contents to C# Page

---

user/languages/haskell.md

When following the guide to setup a Haskell build, travis mistakes the project with a ruby project.
Setting the `language` field explicitly to `haskell` resolves this issue.

Following the Haskell guide leads to ruby builds

---

user/reference/xenial.md

The correct name for the package to be installed instead of causing an error is `google-chrome-stable`.

Fix package name for Google Chrome in Xenial

---

user/languages/perl6.md

Adds documentation for https://github.com/travis-ci/travis-build/pull/1643

Document .t6 extension for perl6 test files

---

user/apps.md

A lightweight abstraction layer for using Travis CI version 3 of their API.  This gem has no dependencies, fully documented API interface methods with examples, and 100% test coverage.

Ruby gem trav3 - API v3 client

---

user/enterprise/platform-tips.md
user/notifications.md

Lets Encrypt certificates need to be renewed every 90 days rather than a user forgetting to do that this provides them with instructions on how to create a cronjob to do that automatically. The only process they need to do externally is communicating with their users whenever there will be downtime for the renewal to take place.

Instructions on how to create a cronjob for renewing Lets Encrypt certificates

---

user/languages/cpp.md
user/languages/elixir.md
user/languages/go.md
user/languages/java.md
user/languages/php.md
user/languages/scala.md

@plaindocs replacing https://github.com/travis-ci/docs-travis-ci-com/pull/2254 because I deleted that fork

naming minimal file examples in all ataglance side panels

---

user/languages/php.md

This was changed in https://github.com/travis-ci/php-src-builder/pull/28.

PHP nightlies do not include 3rd-party extensions

---

user/languages/elixir.md
user/languages/elm.md
user/languages/erlang.md
user/languages/php.md
user/languages/python.md
user/languages/ruby.md

Python is the only language without a default script in its at-a-glance side panel. Should Python's script default to `pytest`?

making ataglance minimal examples as minimal as possible

---

user/conditions-v1.md

As explained in [here](https://travis-ci.community/t/somewhat-misleading-documentation-on-conditions/2468), the equals comparison on `tag` checks if it had a name `true`. The term true also represents the boolean value `true` and easily confuses a user. Therefore it would be better to make the documentation unambigous by having an example such as `tag = bar`.

Equals comparison on tag is based on its name.

---

user/build-stages.md

Slight change to sentence "Stages group jobs that run in parallel and different stages run sequentially." for clarity.
Credit to @iriberri :)

Improve stages grouping jobs sentence for clarity

---

user/enterprise/platform-tips.md

Adds instructions for how to run the 'services to webhooks' migration that will be added in 2.2.8.

Add GitHub services to webhooks migration info to enterprise platform admin tips

---

user/languages/python.md

Removes Python 3.4 from one example because that release has reached its end of life.
* https://devguide.python.org/devcycle/#end-of-life-branches
This PR does _not_ remove Python 3.4 from line 48 where it appears with other EOLed versions of Python (2.6 and 3.3) that Travis CI continues to make available.

Remove Python 3.4 from this example because it is EOL

---

user/languages/python.md

"3.7-dev" in Trusty is pre-release Python 3.7.
"3.7-dev" on Xenial is the current 3.7 development branch
@plaindocs Your review please.

Clarify that dist: xenial is required for all Python >= 3.7

---

user/migrate/legacy-services-to-github-apps-migration-guide.md

Per https://developer.github.com/v3/guides/replacing-github-services/#deprecation-timeline
> January 31, 2019: GitHub will stop delivering installed services' events on GitHub.com.

Fix year of github services deprecation

---

_data/snippets.yml
user/enterprise/custom-queues.md
user/enterprise/high-availability.md
user/enterprise/platform-tips.md
user/enterprise/precise.md
user/enterprise/setting-up-travis-ci-enterprise.md
user/enterprise/ssl-certificate-management.md
user/enterprise/troubleshooting-guide.md
user/enterprise/upgrading.md
user/enterprise/worker-cli-commands.md
user/enterprise/worker-configuration.md

This is a followup based on [this comment](https://github.com/travis-ci/docs-travis-ci-com/pull/2280#discussion_r263014787) from @plaindocs.
Summary of the changes:
* Break apart instructions into separate sections
* Use a numbered list for the steps of the instructions in each section
* General language updates for readability and clarity

Refactor Lets Encrypt section of Enterprise SSL Management page

---

user/deployment/pypi.md

The indentation on the "release to a different pypi index"
example was over indented compared to the other examples.

Fix over indentation on release example

---

user/database-setup.md

We dropped support starting on Xenial and the information on default settings was no longer true since the last Trusty updates https://github.com/travis-ci/travis-cookbooks/commit/042766636ba9aa95fbe996f281048c543d0f0b90
With those changes, the default configuration in the VM (`/etc/riak/riak.conf`) now has:
```
storage_backend = bitcask
search = off
```

Update Riak service details

---

user/deployment/pages.md

GitHub Pages uses `gh-pages`, not `gh_pages`

GitHub Pages: Fix default branch name

---

user/common-build-problems.md

Missing slash causes a link that was intended to be absolute to be relative and lead to a page that doesn't exist. I think this is the actual location you want to redirect people to.

Fix Broken Link in Common Build Problems

---

user/sonarcloud.md

We recently encountered this issue:
https://community.sonarsource.com/t/github-check-quality-gate-of-new-coverage-fails-after-refactiong-untested-classes/8904
So I thought this information might be helpful for other Travis CI / SonarCloud users.

Add section on accessing full SCM history

---

user/conditions-v1.md

I'm assuming `foo =~ bar` means `bar` matches `foo`, and `foo !~ bar` means `bar` _does not_ match `foo`

Fix missing negation in regex example

---

user/encryption-keys.md

Instead of a wall of text, use a table to visually break up and present information in a more concise way.
This is a follow-up to #2420.

Clean up public key retrieval instructions

---

user/reference/xenial.md

https://github.com/travis-ci/travis-build/pull/1678

Python 3 is now the default, not legacy Python

---

user/languages/r.md

I suggest to replace 'Linux' with Ubuntu, that is the Linux distro which is referred here with those version names.
Being a Linux user myself (but not at all familiar with CI), I also have a question on this: to me it seems remarkable to use Ubuntu versions that have become outdated and hence, will have older versions of libraries such as GDAL etc. than what typical users nowadays have available.
See https://ubuntu.com/about/release-cycle , especially the long-term-supported (LTS) releases (note: precise = 12.04, trusty = 14.04). Currently Ubuntu is at LTS 18.04 (Bionic) and next year in April will see LTS 20.04.
Also, R-packages for Ubuntu on CRAN ([link](https://cran.r-project.org/bin/linux/ubuntu/)) are not provided anymore for Ubuntu Precise.
Sorry if I misunderstood the whole aim …

Precise & Trusty are versions of Ubuntu

---

user/encryption-keys.md

The string being encrypted had a `B` where there should have been a `b`

Type in 'escaping certain symbols' example

---

user/languages/javascript-with-nodejs.md

While setting up my first JS project using TravisCI (https://travis-ci.org/SidOfc/babel-plugin-transform-media-imports) my project was identified as a Ruby project while I had specifically set `language: node_js` and some versions, each enclosed by strings:
```yml
node_js:
- "12.0.0"
- "11.0.0"
```
To fix the issue I had to remove the quotes:
```yml
node_js:
- 12.0.0
- 11.0.0
```
This minimal change just removes the quotes from the version so that users that are new to either TravisCI or JS have one less bump to overcome :)

Remove quotes from NodeJS version example

---

user/gui-and-headless-browsers.md

I don't think it's best practice, even though there is just one variable, to define it as a test matrix entry.

MOZ_HEADLESS=1 should be set as a global env

---

user/running-build-in-debug-mode.md

`ctrl-b 1` led to the error message `Window not found: :=1`.
Same for `ctrl-b 0`. (Yes, I created a new window using ``ctrl-b c` beforehand.
So I am happy that I discovered another way to switch windows.
Maybe this helps others, too.

Add more commands to switch between windows.

---

user/enterprise/xenial.md

Added links to the Xenial build environment documentation to let Enterprise customers know the changes that have occurred with the Xenial environment.

Update Xenial Enterprise docs to mention changes from Trusty

---

_includes/deploy/shared.md

This PR fixes a URL where the `http://localhost:4000` prefix was still included and therefore not linkable on the deployed [docs pages](https://docs.travis-ci.com/user/deployment-v2/providers/npm/#see-also)

Removed localhost:4000 in URL

---

_includes/deploy/providers/npm.md

This PR adds the `dry_run` option in the documentation for the [npm provider](https://docs.travis-ci.com/user/deployment-v2/providers/npm/).
It is based on the according PR in the **travis-ci/dpl** repository: https://github.com/travis-ci/dpl/pull/1114, which should add a `--dry-run` CLI parameter, whenever a test run is preferred, without actually uploading the package to the repository.
Therefore a `dry_run: true` in the **.travis.yml** should be the equivalent to `npm publish --dry-run` in the CLI.

Add dry_run option in npm docs

---

user/languages/clojure.md

As per https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/clojure.rb#L30
`project.clj` cannot be run directly so the current info is not an equivalent to that

Fix false info on default command

---

user/languages/python.md

The specified path is invalid for the other versions (current default ver is 3.8)

Add explicit python version to the choco package

---

user/languages/rust.md

Thanks to @BanzaiMan who reviewed https://github.com/travis-ci/travis-build/pull/1799, I'm creating the current PR to modify the documentation about how the `rust` builder is made.

Use rustup 'minimal' distribution by default

---

user/languages/julia.md

This seems to work fine, but is not documented:
https://github.com/travis-ci/travis-build/blob/ead50a6790a3e48c75c3459a017faf743c6246be/lib/travis/build/script/julia.rb#L188-L190
I was already using this since https://github.com/JuliaCI/Appveyor.jl does the same.
cc @ararslan

Julia; document major version selector

---

user/languages/rust.md

As mentioned in a comment on a previous PR https://github.com/travis-ci/docs-travis-ci-com/pull/2565#discussion_r336368906, the link can now point to the official documentation thanks to https://github.com/rust-lang/rustup.rs/pull/2072.

Update the link for Rustup profiles

---

user/languages/ruby.md

* Since Bundler 2.0.1, it does not help to `gem update --system` and only slows down the build.
* TravisCI seems to always use Bundler 1.0 by default: https://travis-ci.org/eregon/mspec/builds/600094360

Improve and fix Bundler 2.0 docs

---

_includes/head.html
user/languages/erlang.md
user/languages/python.md

tablefilter.js is quite heavy at 1.9 MB, and unless it's absolutely
necessary, we should not load it.
Ideally, we should replace this will a smaller library (or a small
JavaScript code) to provide the required functionality.

Load tablefilter.js only when necessary

---

user/languages/nix.md

Reverts travis-ci/docs-travis-ci-com#2578
Because https://github.com/travis-ci/travis-build/pull/1804 was reverted.

Revert "Default Nix version: 2.0.4 -> 2.3.1"

---

_data/xcodes.yml

This list is based on the output of `xcrun simctl list` on the `xcode11.2` image (Xcode 11.2.1, build version 11B500). For example, see [SwifterSwift/SwifterSwift’s job #3025.1](https://travis-ci.org/SwifterSwift/SwifterSwift/jobs/614840490#L178-L593).

Update simulators of xcode11.2 image

---

user/languages/haxe.md

Re https://github.com/travis-ci/travis-build/commit/faa06426f1ecc08c096d029d4afc137c5758b8dd

Haxe support: default Neko version is now 2.3.0

---

user/environment-variables.md

Clarify that `TRAVIS_TAG` is set to the empty string for non-tag builds. From the current formulation I had (mistakenly) assumed that it was unset instead of set to the empty string.

Clarify that TRAVIS_TAG is set (but empty) for non-tag builds.

---

user/languages/php.md

Provide information on supported distributions for PHP 5.6, and 7.0.
Also note that PHP 7.4 is not supported on Precise.
Confirmed via https://travis-ci.org/andrewnicols/fun/builds/623459357

Update information regarding PHP version and distribution support

---

Rakefile
user/ip-addresses.md

This change adds new IP addresses for us-east1 zone: https://docs.travis-ci.com/user/ip-addresses/

Add us-east1 ip addresses

---

user/environment-variables.md

`gem install travis` fails on a default mac installation. `brew install travis` works. https://github.com/travis-ci/travis-ci/issues/2055

mention `brew install travis`

---

user/languages/ruby.md

I discovered this was necessary after upgrading to Bundler 2.1.0 yesterday,
only for CI to break when 2.1.1 came out today.
See also: https://github.com/faker-ruby/faker/pull/1867
The docs should maybe also emphasize that the specific version being installed should be explicitly set (e.g. `gem install bundler:2.1.1`) to prevent builds from breaking when new versions come out, but I didn't do that here.

Update 'Building Ruby' docs with another fix for Bundler 2.0

---

user/reference/bionic.md

Appears out of date. See my recent build:
https://travis-ci.org/citation-style-language/styles/builds/626802555#L160
Not sure how to easily check the default ruby version.

Update pre-installed Ruby versions in Bionic

---

user/reference/windows.md

There is [demand](https://travis-ci.community/t/3658) for MSYS2 in the Windows environment, but the installation and use of it is rather tricky. Document it for the time being, until the day it is incorporated into the image.

Add guidance for using MSYS2 in Windows

---

user/languages/d.md

The Github repository linked now redirects to the community forum.
Additionally, specify a more recent version of DMD as example so as not to look outdated.

Update dlang documentation

---

user/reference/windows.md

* Replaced $* with "$@"
$* does not parse commands with spaces correctly. E.g. `$mingw64 cmake -G"MSYS Makefiles" ..` will fail because of the space after MSYS.
It will parse as just $mingw64 cmake -G"MSYS
* ~~Commented out MAKE=mingw32-make
This is inconsistent with the mingw64 installation described, and will fail on tools like cmake. As it is highly specific, I commented it out.~~

Updated Windows/MSYS2 documentation

---

user/deployment-v2/providers/netlify.md

I tried today the travis v2 deploy to netfliy option and red this
documentation for it: https://docs.travis-ci.com/user/deployment-v2/providers/netlify/#deploying-a-specific-directory
In the part `known options` it mentions, that when I want to deploy a
specific folder it needs to be defined with the option `dir`
On the bottom of the documentation is an area `Deploying a specific
directory` that wants `local_dir` as a parameter. When I specify
`local_dir` it tells me that the option does not exist. With `dir` it
works.
Let me know what you think of this change and thanks in advance for reviewing.

Use dir instead of local_dir

---

user/languages/julia.md

Side note: It would be great to have a working example of a `.travis.yml` file with both a `documentation` and an `allow_failures` section that works!

fix typos in julia.md

---

user/reference/xenial.md

Hi guys,
I hope you're well.
This is a very tiny change just to keep consistency throughout the document xenial.md. There is one place where the travis file was referred as `travis.yml` instead of `.travis.yml`
BR,
Hussama

minor change to keep consistency in xenial.md

---

user/status-images.md

Project has been moved to travis.com, the example badge was broken.

Fixed the badge on status-images.md

---

user/job-lifecycle.md

The origin text
> Using exit inside a custom script which will be invoked from during a build is fine.
is confusing to read because it appears to either be missing words or to be the left over from a previous edit. "invoke from during" is not standard English usage.
This PR updates the text to indicate that using exit is safe and that it will have the expected result of marking the task as failed.

Suggest better wording for 'inside a custom script'

---

user/deployment-v2/conditional.md

Fixes a typo in the all_branches code example where it was written `all_branch`

Fix typo in all_branches example

---

user/environment-variables.md

The concensus at https://travis-ci.community/t/travis-incorrectly-double-quotes-environment-variables/7496 is the current way is the most intuitive.

Document the format for environment variables' values

---

user/environment-variables.md

In https://github.com/travis-ci/docs-travis-ci-com/pull/2720, I've mixed up the name of the added anchor so the intra-page link didn't work.
Also put the anchor above the linked note -- this way, the note looks better when following the link to the anchor.

fix anchor name

---

user/environment-variables.md

I believe this is a typo, or leftover from some old syntax. The description says to use "global" and "matrix" keys, but the example `.travis.yml` uses "global" and "jobs" keys.

Environment Variables: matrix -> jobs

---

user/environment-variables.md

The yaml example uses the key "jobs" in favor "matrix" (I believe from older versions of the specification). This change updates the language in the description text to match what's found in the example.

Use "jobs" in favor of "matrix" in Global Vars description

---

user/languages/dart.md

Dart has a new versioning scheme (https://github.com/travis-ci/travis-build/pull/1897 adds Travis support for that) and a new beta channel.
Part of https://github.com/dart-lang/sdk/issues/40996.

Update documentation for Dart's new version scheme

---

user/installing-dependencies.md

Ubuntu/linux command is snap not snaps ... that's all

Typo error in Snaps Addon section

---

user/gui-and-headless-browsers.md

The Chrome and Firefox headless sections should not be nested under the xvfb section, as they do not require xvfb.  With this change, those sections will appear in the ToC at the top of the page.

Top-level headers from Chrome and Firefox headless

---

user/deployment-v2/providers/cloudformation.md

Wrong URL linking to another service was used.
Users are currently redirected to https://convox.com/ instead of AWS CloudFormation doc page when they click on the link.

Fix Incorrect URL to AWS CloudFormation Doc Page

---

user/for-beginners.md

I found the existing order of the "common words" confusing:
1. First phases are mentioned as the steps of jobs
2. Then jobs, which have a series of phases
3. Then builds, which are groups of jobs
4. Finally stages, which are again groups of jobs
I had to jump around the list quite a lot to understand the hierarchy and the different between the words here. I think this new ordering should be easier to understand.

Reordered the common words

---

user/job-lifecycle.md

On page `https://docs.travis-ci.com/user/job-lifecycle/` there is a paragraph with `The .travis.yml file describes the build process. A build in Travis CI is a sequence of stages.`.
The link of 'stages' links to `build-stages` which is the URL of `https://docs.travis-ci.com/user/job-lifecycle/build-stages`, this gives a 404 on visit, and the correct link should be `https://docs.travis-ci.com/user/build-stages/`.
This is a quick fix on that link.

Fix 404 link on 'job-lifecycle'

---

user/sonarcloud.md

The SonarCloud scanner is going to require Java 11 soon, so we want to update all the existing documentation to reflect this change.
We also took the opportunity to update the SonarCloud description

Update SonarCloud documentation

---

.travis.yml

Looks like Xenial's certificates are no longer valid to verify https://language-archives.travis-ci.com.
We could update the package `ca-certificates`, or use a more recent Ubuntu release.

Use bionic

---

user/triggering-builds.md

As outlined on [the forums](https://travis-ci.community/t/merge-mode-replace-seems-to-merge-lists-not-replace-them/8839/3), the docs don't correctly outline where the `merge_mode` key should be placed in the API request.
This PR fixes that.

Update triggering-builds.md with correct `merge_mode` example

---

user/languages/nix.md

Changing default Nix version from 2.0.4 to 2.3.6 per https://github.com/travis-ci/travis-build/pull/1833

Update nix default version to 2.3.6

---

user/reference/windows.md

Julia has been supported on Windows since August 2019 🎉
Have a look at:
- [the announcement](https://discourse.julialang.org/t/julia-is-now-available-on-travis-windows-builds/27187/2)
- a project that tests Julia on Windows: [https://travis-ci.org/github/ararslan/Jackknife.jl](https://travis-ci.org/github/ararslan/Jackknife.jl)
- the [`.travis.yml` file](https://github.com/ararslan/Jackknife.jl/blob/master/.travis.yml) of that project
I also put the list of languages in **alphabetical order**, hence the multiple changed lines.

included Julia in supported Windows languages

---

user/languages/rust.md

In latest Cargo `--all` flag is deprecated in favor of `--workspace`. This PR updates documentation for Rust to reflect this.

Use `--workspace` instead of `--all` in rust.md

---

user/languages/erlang.md

No one is testing on OTP 17.5 or 18.x any more. It would
be more useful to have examples that use
Erlang 23.0.x and 22.3.x.

Update Erlang/OTP release examples

---

user/languages/matlab.md

Currently, the free MATLAB language support is enabled for public repositories. In this pull request, we update the documentation for MATLAB language to reflect this support for public repositories.
Thanks for your consideration.

add note about support for public repos using MATLAB

---

user/migrate/open-source-repository-migration.md

Addressing feedback from experimental migration og grouped account from .org to .com
Providing process guidelines for such case - it's rare, but it occurs
Migration of such accounts is usually done because .com has some feature not present in .org

Adding explanation on migrating grouped account

---

user/languages/julia.md

Fixed 404 link in [Julia document](https://docs.travis-ci.com/user/languages/julia/).
https://julialang.org/downloads/nightlies.html -> https://julialang.org/downloads/nightlies/

Fix 404 link in julia doc

---

_data/snippets.yml
user/migrate/open-source-repository-migration.md
user/tutorial.md

Add pre-explanation on the warning people do get from GitHub due to OAuth scopes Travis CI uses.
Teams are scared off by first-time sign-in warning received from GitHub, particularly about write access to all private and public repositories. This prevents them from moving to travis-ci.com, as they do not agree to activate Travis CI OAuth GitHub App, which actually is needed in the process, but does no harm when accessing users repository.

Sign in to travis-ci.com and GitHub warning

---

user/travis-ci-for-private.md

The link https://travis-ci.com/account/subscription showed this error:
> We couldn't display the repository
> account/subscription

Fix link to billing page

---

user/billing-overview.md

Hello 👋 
I noticed a small typo while reading through the new billing section

docs: fix typo in billing_overview page

---

user/database-setup.md

Update documentation on how to specify alternate versions of PostgreSQL.
This took a while to figure out all of the nuances.  But it is tested for 9.4, 9.6, 10, 11, and 12. ( see https://travis-ci.com/github/SchemaPlus/schema_plus_functions/builds/215791997/config )

Add clarification on configuring different versions of PostgreSQL

---

user/reference/focal.md

Was debugging a Compose issue (I was trying to use Compose file version 3.8, which was added in docker-compose 1.25.5) when I noticed these stale docs.
Output from debugging in this environment:
```yaml
arch: arm64-graviton2
virt: lxd
os: linux
dist: focal
```
```
$ docker-compose version
docker-compose version 1.25.1, build a82fef0
docker-py version: 4.2.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```
```
$ docker version
Client:
Version:           19.03.8
API version:       1.40
Go version:        go1.13.8
Git commit:        afacb8b7f0
Built:             Wed Mar 11 23:43:15 2020
OS/Arch:           linux/arm64
Experimental:      false
Server:
Engine:
Version:          19.03.8
API version:      1.40 (minimum version 1.12)
Go version:       go1.13.8
Git commit: …
```

Fix docker-compose version in `dist: focal` env

---

_data/snippets.yml
_includes/deploy/providers/testfairy.md
user/billing-overview.md
user/jwt.md
user/multi-cpu-architectures.md
user/notifications.md.erb

As found in https://github.com/travis-ci/docs-travis-ci-com/pull/3031 here https://github.com/peternewman/docs-travis-ci-com/runs/2866955655?check_suite_focus=true

Fix various typos

---

user/billing-overview.md

When subscribing to a concurrency plan, the following message is shown "Please note that you will be charged monthly for the unique users who triggered builds.", which made me think I might be charged the cost of the concurrency plan x the number of users.
I contacted the support and was told that it is actually meant for usage-based plans only, so I think stating it plainly in the linked documentation would save support requests.

Clarify user billing for concurrency plans

---

user/status-images.md

✓ travis-ci.com requires app subdomain (or ~/github/... vdir) or 404's
✓ unlink 'private repositories' link to root domain
✓ switch .org to .com
I dare someone to run a 404 scanner on the entire site, I'll fix these because finding the Build Status page from a bunch of projects on GitHub 404.

Use generated URLs; unlink 'private repositories'

---

user/enterprise/tcie-3.x-setting-up-travis-ci-enterprise.md

Added even more explicit clarfications, as apparently not everyone spots two machines requirement mentioned in the prerequisities section, which causes confusion during deployment.

Even more explicit description of two parts of TCIE

---

user/travis-ci-vcs-proxy-get-started.md

Added info on where to exactly the Travis CI build definition must be located in SVN and/or Perforce repository

.travis.yml location in SVN and Perforce

---

user/sauce-connect.md

The Sauce Labs Wiki has been replaced with the Sauce Labs Documentation site.
In the Sauce Labs Documentation, tunnel-identifier has been deprecated and replaced with tunnel-name.
https://docs.saucelabs.com/secure-connections/sauce-connect/setup-configuration/basic-setup/#using-tunnel-names

Updates docs links and replaces tunnel-identifier

---

user/best-practices-security.md

The term "log scan" which the customer sees in the UX is not highlighted and so is difficult to find. This PR adds a heading to the section about log scans. (Sorry, I also changed the first paragraph around a bit. Feel free to ignore that bit - force of habit!)

Make it easier to find log scan information

---

user/sonarcloud.md

Default JDK i.e. 11, is soon going to be deprecated for Sonarcloud scans, see: https://community.sonarsource.com/t/java-11-is-deprecated-as-a-runtime-env-to-scan-your-projects/96597
A warning appears in the build job logs as well, https://app.travis-ci.com/github/test-runs-tci/rspec_ruby_tci/jobs/608556166#L344
Using `jdk: openjdk17` sets up the JRE/JDK 17 thereby making the build job happy, https://app.travis-ci.com/github/test-runs-tci/rspec_ruby_tci/jobs/608557732

Update sonarcloud.md to specify JDK 17

---

user/apps.md

Removed screenshot for Screensaver Ninja (MacOS) that looks like it was left in by mistake. App appears to have been discontinued and previously removed from this page, but screenshot was not under correct heading so it got missed, slightly breaking the page layout.
Should correct this layout misalignment:

Update apps.md - Removed unused screenshot

---

_includes/enterprise_sidebar.html
_includes/sidebar.html
user/open_source_licence.md

Added the EmberJS MIT License as a sidebar notice. 
The notice was added to both the docs sidebar and the Enterprise sidebar. 
Please review

Emberjsmitlicense

---

404.html
_includes/head.html
_layouts/en.html
_layouts/en_enterprise.html
_layouts/nodocs.html

Removed `ga-tag` since I've added the new one that's GA-4 compatible (GTM), in `en.html` and that seems to inherit all other pages given that it's Jekyll based and in the interim Ruby based. 
The PR: https://github.com/travis-ci/docs-travis-ci-com/pull/3366/commits/20b8e73630183b314646daee5942ee3353ff0329
Is the latest one. That should work. 
Steps:
* Removed GTM tag in `head.html`
* Added inside the <head> tag that inherits, the new GTM tag, and this should inherit throughout the docs. 
e.g.

Remove ga-tag since it's moved to `en.html` and inheritance will follow.

---

user/environment-variables.md
user/languages/go.md

GO docs update
